# Настройки проекта LAIRD
# После изменения перезапустите сервер.

donate = 4000
money = 70000000
vip = 1
lvl = 8

nameserver = SHTORM RUSSIA 
tg = t.me/shtorm_russia
vk = vk.com/shtorm_russia
site = none 

whitelist = смотри файл whitelist.ini
full_access_name = Owner_Name

audio_url = http://example.com/menu.mp3
chat = {FFCD00}Чат был очищен администрацией
