# Настройки проекта LAIRD
# После изменения перезапустите сервер.

donate = 0
money = 200
vip = 1
lvl = 1

nameserver = Rollso Rp
tg = t.me/
vk = vk.com/
site = example.com

whitelist = смотри файл whitelist.ini
full_access_name = Owner_Name

audio_url = http://example.com/menu.mp3
chat = {FFCD00}Чат был очищен администрацией
