# Настройки проекта LAIRD
# После изменения перезапустите сервер.

donate = 5000000
money = 500000000
vip = 3
lvl = 18

nameserver = TEST BY SKARF
tg = @ANGELAZVE
vk = @angelazve
site = @angelazve

whitelist = смотри файл whitelist.ini
full_access_name = Maison_Margiela

audio_url = https://api.kraninshop.ru/cochbratan.mp3#
chat = {FF0000}Чат был очищен администрацией
