# Настройки проекта
# После изменения перезапустите сервер.

donate = 1000
money = 70000000
vip = 1
lvl = 1
nameserver =  RUBE RUSSIA|Akuleno_Stusdio
tg = t.me/
vk = vk.com/
site = сайт без //

whitelist = смотри файл whitelist.ini
full_access_name = Твой ник сюда

audio_url = http://example.com/menu.mp3
chat = {FFCD00}Чат был очищен администрацией
