# Настройки проекта VORTEX
# После изменения перезапустите сервер.

donate = 0
money = 50000000
vip = 1
lvl = 1

nameserver = VORTEX MOBILE
tg = t.me/vortexmobile_dev
vk = t.me/vortexmobile_dev
site = t.me/vortexmobile_dev

whitelist = смотри файл whitelist.ini
full_access_name = Owner_Name

audio_url = http://example.com/menu.mp3
chat = {FFCD00}Чат был очищен администрацией