# Настройки проекта
# После изменения перезапустите сервер.

donate = 125
money = 500000
vip = 1
lvl = 1

nameserver = META RP
tg = t.me/crmp_meta
vk = vk.com/crmp_meta
site = metarp.samp.date

whitelist = смотри файл whitelist.ini
full_access_name = Твой ник сюда

audio_url = http://example.com/menu.mp3
chat = {FFCD00}Чат был очищен администрацией
