/* Интерьеры */
enum {
	INTERIOR_NONE = 0,
	G_ECO_INTERIOR = 20,
	G_GTA5_INTERIOR = 30,
	LCN_INTERIOR,//31
	RM_INTERIOR,//32
	YAKUZA_INTERIOR,//33
	DUEL_HOLL_LOBBY,//34//WORLD 1
	AIM_DEAGLE_DM,//35 //World 1
	DM_2_EXTERIORS,//36 //World 1
	YACHT_INTERIOR,//37 - world -1
	HOSPITAL_SF_INT, //38 - Wolrd - 1
	MAD_HOUSE_INT,//39 - World - 10
	FAMILY_INT_0,//40 - World - -1
	FAMILY_INT_1,//41 - World - -1
	FAMILY_CENTER_INT,//42 - WORLD - 1
	HOSPITAL_LV_INT, //43 - WOLRD - 1
	HOSPITAL_ARMY_INT, //44 - WORLD - -1
	NEWS_AGENCY_INT, //45 - WORLD - -1
	DRUGS_LAB_INT, //46 - WORLD - -1
	BIKERS_INT, //47 - WORLD - -1
	GARAGE_E_INT, //48 - WORLD - -1
	GARAGE_B_INT, //49 - WORLD - -1
	GARAGE_A_INT, //50 - WORLD - -1
	GARAGE_S_INT, //51 - WORLD - -1
	DEER_HUNTER_INT, //52 - WORLD - -1
	FACTORY_INT,//53 - WOLRD - FACTORY_WORLD (1)
	PIRUS_INTERIOR,//54 - WORLD - -1
	KAUTA_SFA,//55 - WORLD - 1
	CARAVAN_INTERIOR//56 - WORLD - -1
	
} 

/* Закупка дальнобойщики */
enum {
    LOADING_SAWMILL_0,
    LOADING_SAWMILL_1,
    LOADING_COAL_0,
    LOADING_COAL_1,
    LOADING_OIL_0,
    LOADING_OIL_1,

    LOADING_ALL
}
/* Дипломатия */
enum {
	sDIP_NEUTRAL, //sDIP_NEUTRAL,
	sDIP_WAR,//sDIP_WAR,
	sDIP_ALLIANCE,//sDIP_ALLIANCE,
	sDIP_ALLIANCE_SET,//sDIP_ALLIANCE_SET,
	sDIP_ALLIANCE_GET//sDIP_ALLIANCE_GET
}
/* Лицензии */
enum {
	DRIVE_LIC,
	FLY_LIC,
	BOAT_LIC,
	FISH_LIC,
	GUN_LIC,
	NONE_LIC 
}
/* Мини игры */
enum {
	ACTION_NONE,
	ACTION_ROB_HOUSE,
	ACTION_TAKE_ATM_CASH,
	ACTION_HUNTER_DEER,
	ACTION_FACTORY_SORT
}
/* Типы сообщений */
enum {//sliv Message
	sqlTextSellHouse = 0,
	sqlTextBuyFerm,
	sqlTextSellFerm 
} 
/* Счет /warstats (/capture, /bizwar, /bikerswar) */
enum {//0 - Warn / 1 - Kick / 2 - Ban / 3 - Prison
	REASON_WARN = 0,
	REASON_KICK,
	REASON_BAN,
	REASON_PRISON
}
/* Авторынки */
enum {
	TYPE_COST_CASH = 0,
	TYPE_COST_POINT
}
/* Типы транспорта */
enum {
	TYPE_CAR = 0,
	TYPE_BOAT,//1
	TYPE_PLANE,//2
	TYPE_CARAVAN//3
}
/* Me Action */
enum
{
	SELECT_ACTION_IN_CHAT = 0,
	SELECT_ACTION_IN_BUBBLE,
	SELECT_ACTION_GENERAL
}
/* Фракции */
enum {
	INVALID_FRACTION_ID = 0,
	FRACTION_LSPD,//1
	FRACTION_FBI,//2
	FRACTION_ARMY_SF,//3
	FRACTION_HOSPITAL_SF,//4
	FRACTION_LCN,//5
	FRACTION_YAKUZA,//6
	FRACTION_CITYHALL,//7
	FRACTION_PIRUS,//8
	FRACTION_SF_NEWS,//9
	FRACTION_SFPD,//10
	FRACTION_AUTOSCHOOL,//11
	FRACTION_BALLAS,//12
	FRACTION_VAGOS,//13
	FRACTION_RUSSIAN,//14
	FRACTION_GROVE,//15
	FRACTION_LS_NEWS,//16
	FRACTION_AZTEC,//17
	FRACTION_RIFA,//18
	FRACTION_ARMY_LV,//19
	FRACTION_LV_NEWS,//20
	FRACTION_LVPD,//21
	FRACTION_HOSPITAL_LS,//22
	FRACTION_HOSPITAL_LV,//23
	FRACTION_MONGOLS_MC,//24
	FRACTION_BANDIDOS_MC,//25 Bandidos FRACTION_BANDIDOS_MC
	FRACTION_OUTLAWS_MC//26//Outlaws
}
 
/* Работы */
enum {
	JOB_NONE,//0
	JOB_BUS_ROUTE,//1
	JOB_TAXI,//2
	JOB_HOTDOG,//3
	JOB_MECHANIC,//4
	JOB_DELIVERY,//5
	JOB_COACH,//6
	JOB_TRUCKER,//7
	JOB_COLLECTOR,//8
	JOB_FOREMAN,//9
	JOB_THEFT_CAR,//10
}
/* Индексы аттача */
enum {
    ATTACHED_SLOT_JOB_0 = 0,
    ATTACHED_SLOT_JOB_1,// = 1
    ATTACHED_SLOT_JOB_2,// = 2
    ATTACHED_SLOT_ITEMS_0,// = 3
    ATTACHED_SLOT_ITEMS_1,// = 4
    ATTACHED_SLOT_ITEMS_2,// = 5
    ATTACHED_SLOT_ITEMS_3,// = 6
    ATTACHED_SLOT_ITEMS_4,// = 7
    ATTACHED_SLOT_ITEMS_5,// = 8
    ATTACHED_SLOT_ITEMS_6,// = 9
}
/* Диалоги */
enum {
	D_NULL,
	D_REG_PASSWORD,// 1
	D_REG_RULES,// 2
	D_REG_RULES_0,// 3
	D_REG_EMAIL, // 4
	D_REG_REFERAL,// 5
	D_REG_SEX,// 6
	D_LOGIN_PLAYER,// 7 
	D_VK_GUARD_CONFIRMATION,
	D_TG_GUARD_CONFIRMATION,
	D_VK_GUARD_INPUT,//
	D_TG_GUARD_INPUT,
	D_JOB_TAXI_CLIENT,
	D_JOB_TUCKER_LOAD,
	D_JOB_FERM_LOAD,
	D_JOB_FARM,
	D_LOGIN_TRANSFER,
	D_LOGIN_TRANSFER_0,
	D_CANCEL_COMMAND, 
	D_FARM_FUNC_0,
	D_FARM_FUNC_1,
	D_FARM_FUNC_2,
	D_FARM_FUNC_3,
	D_FARM_FUNC_4,
	D_FARM_FUNC_5,
	D_FARM_FUNC_6,
	D_FARM_FUNC_7,
	D_FARM_FUNC_8,
	D_TUNING_FUNC_0,
	D_TUNING_FUNC_1, 
	D_STO_FUNC_0,
	D_STO_FUNC_1,
	D_STO_FUNC_2,
	D_STO_FUNC_3,
	D_STO_FUNC_4,
	D_STO_FUNC_5,
	D_STO_FUNC_6, 
	D_DUEL_MENU,
	D_DUEL_CREATE_MONEY,
	D_DUEL_CREATE_GUN,//40
	D_DUEL_CREATE,
	D_DUEL_SETTING,
	D_DUEL_INFO,
	D_DUEL_TYPE,
	D_DUEL_TEAM, 
	D_INSTRUSCTOR_EXIT,
	D_RESPAWN_FRAC_CAR,
	D_SELLARMY_CHAR,
	D_EXIT_BONE,
	D_BONE_STAVKA,
	D_ADMIN_FUNC_0,
	D_ADMIN_FUNC_1,
	D_ADMIN_FUNC_2,
	D_ADMIN_FUNC_3,
	D_ADMIN_FUNC_4,
	D_ADMIN_FUNC_5,
 	//D_ADMIN_FUNC_6, FREE
	D_ADMIN_FUNC_7,
	D_ADMIN_AHELPPANEL,

	D_OBNOVKA_DONATE,

	D_ADMIN_FUNC_8,
	D_ADMIN_FUNC_9,
	D_ADMIN_FUNC_10,
	D_ADMIN_FUNC_11,
	D_ADMIN_FUNC_12,
	D_ADMIN_FUNC_13,
	D_ADMIN_FUNC_14,
	D_ADMIN_FUNC_15,
	D_ADMIN_FUNC_16,
	D_ADMIN_FUNC_17,
	D_ADMIN_FUNC_18,
	D_ADMIN_FUNC_19,
	D_ADMIN_FUNC_20,
	D_ADMIN_FUNC_21,
	D_ADMIN_FUNC_22,
	D_ADMIN_FUNC_23,
	D_ADMIN_FUNC_24,// (/mp)
	D_ADMIN_FUNC_25,
	D_ADMIN_FUNC_26,
	D_ADMIN_FUNC_27,//Freeze Capt's ///80
	D_DYNAMIC_OBJ_0,
	D_DYNAMIC_OBJ_1,
	D_DYNAMIC_OBJ_2,
	D_DYNAMIC_OBJ_3,
	D_DYNAMIC_OBJ_4, 
	D_PLAYER_FISH,
	D_PLAYER_FISH_0,
	D_PLAYER_FISH_1,
	D_PLAYER_FISH_2,
	D_PLAYER_FISH_3,
	D_PLAYER_FISH_4,
	D_PLAYER_FACTORY_0,
	D_PLAYER_test_0, // свободный слот
	D_PLAYER_test_1, // свободный слот
	D_PLAYER_HELP,
	D_JOB_STATS,
	D_JOB_RENT_CAR,
	D_PLAYER_FIHGT_0,
	D_PLAYER_FIHGT_1,
	D_PLAYER_FIHGT_2,
	D_PLAYER_FIHGT_3,
	D_PLAYER_FIHGT_4,
	D_PLAYER_FIHGT_5,
	D_PLAYER_FIHGT_6,
	D_EXAM_AUTOSCHOOL_0,
	D_EXAM_AUTOSCHOOL_1,
	D_RENT_CAR_INC,
	D_AUTOSHOP_SHOW_0,
	D_AUTOSHOP_SHOW_1,
	D_AUTOSHOP_SHOW_2,
	D_AUTOSHOP_SHOW_3,//free
	D_AUTOSHOP_SHOW_4,
	D_AUTOSHOP_SHOW_5,
	D_SELECT_SERVICE_0,
	D_SELECT_SERVICE_1,
	D_SELECT_SERVICE_2,
	D_SELECT_SERVICE_3,
	D_SELECT_SERVICE_4,
	D_PLAYER_ANIMATION,
	D_PLAYER_CLIST,
	D_PLAYER_RADIO,
	D_PLAYER_SPAWNCHANGE,
	D_VEHICLE_HOME_0,
	D_VEHICLE_HOME_1,
	D_VEHICLE_HOME_2,
	D_VEHICLE_HOME_3,
	D_VEHICLE_HOME_4,
	D_VEHICLE_HOME_5,
	D_VEHICLE_HOME_6,
	D_VEHICLE_HOME_7,
	D_VEHICLE_BUY_0,
	D_CITYPHONE_SERVICE,
	D_PLAYER_INVITE,
	D_SELL_DEELER,
	D_PLAYER_SELLCAR_0,//for gos
	D_PLAYER_SELLCAR_1,//for player
	D_VEHICLE_FUNC_0,
	D_VEHICLE_FUNC_1,
	D_VEHICLE_FUNC_2,
	D_VEHICLE_FUNC_3,
	D_VEHICLE_FUNC_4,//130
	D_VEHICLE_FUNC_5,
	D_MAINMENU_FUNC_0,
	D_MAINMENU_FUNC_1,
	D_MAINMENU_FUNC_2,
	D_MAINMENU_FUNC_3,
	D_MAINMENU_FUNC_4,
	D_MAINMENU_FUNC_5,
	D_MAINMENU_FUNC_6,
	D_MAINMENU_FUNC_7,
	D_MAINMENU_FUNC_8,
	D_MAINMENU_FUNC_9,
	D_MAINMENU_FUNC_10,
	D_MAINMENU_FUNC_11,
	D_MAINMENU_FUNC_12,
	D_MAINMENU_FUNC_13,
	D_MAINMENU_FUNC_14,
	D_MAINMENU_FUNC_15,
	D_MAINMENU_FUNC_16,
	D_MAINMENU_FUNC_17,
	D_MAINMENU_FUNC_18,
	D_MAINMENU_FUNC_19,
	//D_MAINMENU_FUNC_20,
	D_MAINMENU_FUNC_21,
	D_MAINMENU_FUNC_22,
	D_MAINMENU_FUNC_23,

	D_MAINMENU_FUNC_24,
	D_MAINMENU_FUNC_25,
	D_MAINMENU_FUNC_26,


	D_MAINMENU_FUNC_27,// supreme

	D_JOB_START_ROUTE, 
	D_SAFE_FAMILY_0,
	D_SAFE_FAMILY_1,
	D_SAFE_FAMILY_2,
	D_SAFE_FAMILY_3,
	D_SAFE_FAMILY_4,
	D_SAFE_FAMILY_5,
	D_SAFE_FUNC_0,
	D_SAFE_FUNC_1,
	D_SAFE_FUNC_2,
	D_SAFE_FUNC_3,
	D_SAFE_FUNC_4,
	D_SAFE_FUNC_5,
	D_UGON_JOB_CAR_0,
	D_UGON_JOB_CAR_1,
	D_UGON_JOB_CAR_2,
	D_BIZZ_AUCTION_0,
	D_BIZZ_AUCTION_1,
	D_BIZZ_AUCTION_2, 
    D_BUY_GOV_GUN,
	D_BUY_GOV_GUN_0,//FBI
	D_BUY_GOV_GUN_1,//Mayor
	D_GOV_CHARITY_0,
    D_GANG_FUNC_0,
    D_GANG_FUNC_1,
	D_MAFIA_FUNC_0,
    D_HOUSE_FUNC_0,
    D_HOUSE_FUNC_1,
    D_HOUSE_FUNC_2,
    D_HOUSE_FUNC_3,
    D_HOUSE_FUNC_4,
    D_HOUSE_FUNC_5,
    D_HOUSE_FUNC_6, // D_HOUSE_FUNC_7, Свободен слот
    D_HOUSE_FUNC_8,
    D_HOUSE_FUNC_9,
    D_HOUSE_FUNC_10,
    D_HOUSE_FUNC_11,//Заселить в дом
    D_HOUSE_FUNC_12,
    D_HOUSE_FUNC_13,
	D_HOUSE_FUNC_14,
	D_HOUSE_FUNC_15,
	D_HOUSE_FUNC_16,
    D_BANK_FUNC_0,
    D_BANK_FUNC_1,
    D_BANK_FUNC_2,
    D_BANK_FUNC_3,
    D_BANK_FUNC_4,
    D_BANK_FUNC_5, //D_BANK_FUNC_6,
    D_BANK_FUNC_7,//Выход из ЧС
    D_BANK_FUNC_8,//200
	D_BANK_FUNC_9, //Edit deposit
	D_BANK_FUNC_10,
	D_BANK_FUNC_11,
	D_BANK_FUNC_12,
	D_BANK_FUNC_13,// Оплата семейного дома
	D_BANK_FUNC_14,// Налог на ТС
	D_BANK_FUNC_15, // Oplata TS
    D_CHANGE_NAME,
    D_RENT_CAR_0,
    D_RENT_CAR_1,
    D_RENT_CAR_2,
    D_RENT_CAR_3,
	D_FINE_CAR_0,
	D_FINE_CAR_1,
    D_NEWS_PANEL_0,
    D_NEWS_PANEL_1,
    D_NEWS_PANEL_2,
    D_NEWS_PANEL_3,
    D_NEWS_PANEL_4,
    D_NEWS_PANEL_5,
    D_NEWS_PANEL_6,
    D_NEWS_PANEL_7,
    D_NEWS_PANEL_8,
    D_NEWS_PANEL_9,
    D_NEWS_PANEL_10,
    D_NEWS_PANEL_11,
    D_NEWS_PANEL_12,
    D_NEWS_PANEL_13,
    D_NEWS_PANEL_14,
    D_NEWS_PANEL_15,
    D_NEWS_PANEL_16,
    D_NEWS_PANEL_17,
    D_NEWS_PANEL_18,
    D_NEWS_PANEL_19,
    D_NEWS_PANEL_20,
    D_NEWS_PANEL_21,
    D_NEWS_PANEL_22,
    D_NEWS_PANEL_23,
    D_SELECT_JOB_GOV_0,
    D_SELECT_JOB_GOV_1,
    D_TAKELIST_PD_0,
    D_TAKELIST_PD_1,
    D_ENTER_PD_0,
    D_ENTER_PD_1,
    D_FRAC_FUNC_0,
    D_FRAC_FUNC_1,//getgun bikers/mafia
    D_FRAC_FUNC_2,
    D_FRAC_FUNC_3,
    D_FRAC_FUNC_4,
    D_FRAC_FUNC_5,
	D_FRAC_FUNC_6,
    D_NEWS_FUNC_0,
    D_NEWS_FUNC_1,
    D_NEWS_FUNC_2,
    D_NEWS_FUNC_3,
    D_NEWS_FUNC_4,
    D_NEWS_FUNC_5,
    D_NEWS_FUNC_6,
    D_NEWS_FUNC_7,
    D_NEWS_FUNC_8,
	D_FRAC_FUNC_9, 
	D_REFERALS,
    D_MDC_PD_0,
    D_MDC_PD_1,
    D_MDC_PD_2,
    D_MDC_PD_3,
	D_ARMY_JOB_0,
	D_ARMY_JOB_1,


	D_BLACK_MARKET_0,
	D_BLACK_MARKET_1,
	D_BLACK_MARKET_2,


    D_ZAKAZ_KILL_0,
    D_ZAKAZ_KILL_1,
    D_ZAKAZ_KILL_2,
    D_ZAKAZ_KILL_3,
    D_ZAKAZ_KILL_4,
    D_ZAKAZ_KILL_5,
    D_START_WORK_FRAC,
    D_MEDIC_HEAL_LOMCA,
	D_MEDIC_HEAL_NARCO,
    D_UNJAIL_GOV, 
    D_DIRECTORY_LIST_0,
    D_DIRECTORY_LIST_1,
    D_DIRECTORY_LIST_2,
    D_DIRECTORY_LIST_3,
    D_DIRECTORY_LIST_4, 
	D_ADMIN_PANEL_0,
	D_ADMIN_PANEL_1,
	D_ADMIN_PANEL_2,
	D_ADMIN_PANEL_3,
	D_ADMIN_PANEL_4,
	D_ADMIN_PANEL_5,
	D_ADMIN_PANEL_6,
	D_ADMIN_PANEL_7,
	D_ADMIN_PANEL_8,
	D_ADMIN_PANEL_9,
	D_ADMIN_PANEL_10,
	D_ADMIN_PANEL_11,
	D_ADMIN_PANEL_12,
	D_ADMIN_PANEL_13,
	D_ADMIN_PANEL_14,
	D_ADMIN_PANEL_15,
    D_GPS_FUNC_0,
    D_GPS_FUNC_1,
    D_GPS_FUNC_2,
    D_GPS_FUNC_3,
    D_GPS_FUNC_4,
    D_GPS_FUNC_5,
    D_GPS_FUNC_6,
    D_GPS_FUNC_7,
    D_GPS_FUNC_8,
    D_GPS_FUNC_9,
	D_GPS_FUNC_10,
	D_GPS_FUNC_11,
    D_RENT_TRUCKER_0,
    D_ATM_FUNC_0,
    D_ATM_FUNC_1,
    D_ATM_FUNC_2,
    D_ATM_FUNC_3,
	D_ATM_FUNC_4,
	D_ATM_FUNC_5,
    D_SELL_HOUSE_GOS,//300
	D_SELL_HOUSE_GOS_0,
    D_JOB_FUNC_0,
    D_JOB_FUNC_1,
    D_JOB_FUNC_2,
    D_JOB_FUNC_3,
    D_JOB_FUNC_4,
    D_JOB_FUNC_5,
    D_JOB_FUNC_6, 
    D_ZONE51_CAM,
    D_DEV_FUNC_0,
    D_DEV_FUNC_1,
    D_DEV_FUNC_2,
    D_DEV_FUNC_3,
    D_DEV_FUNC_4,
    D_DEV_FUNC_5,
    D_DEV_FUNC_6,
    D_DEV_FUNC_7,
    D_DEV_FUNC_8,
    D_DEV_FUNC_9,
    D_DEV_FUNC_10,
    D_ENTER_COST_BIZZ,
	D_DONATE_FAMILIA_2,
	D_DONATE_NAME_2,
    D_DONATE_CODE_0,
    D_DONATE_MENU_0,
    D_DONATE_MENU_1,
    D_DONATE_MENU_2,
    D_DONATE_MENU_3,
    D_DONATE_MENU_4,
    D_DONATE_MENU_5,
    D_DONATE_MENU_6,
    D_DONATE_MENU_7,
    D_DONATE_MENU_8,//Family//330
	D_DONATE_MENU_9,//BoostPack
	D_DONATE_MENU_10,
	D_DONATE_MENU_11,//VIPpack
	D_DONATE_MENU_12,
	D_DONATE_MENU_13,
	D_DONATE_MENU_14,
	D_DONATE_MENU_15,
	D_DONATE_MENU_16, 
	D_DONATE_MENU_17,
	D_DONATE_MENU_18,
	D_DONATE_MENU_19,
	D_DONATE_MENU_20,
	D_DONATE_MENU_21,
	D_DONATE_MENU_22,
	D_DONATE_MENU_23,
	D_DONATE_ACCESORY,
	D_BOOMBOX_RADIO,
	D_BOOMBOX_URL,
	D_BOOMBOX,
    D_UNLOAD_MATERIALS_0,
    D_UNLOAD_MATERIALS_1, 
    D_STATE_PICK_0,
    D_STATE_PICK_1,
    D_STATE_PICK_2,
	D_STATE_PICK_3,
	D_FIXCAR_0,
	D_FIXCAR_1,
	D_PROMO_CODE_0,
	D_PROMO_CODE_1,
	D_PROMO_CODE_2,
	D_PROMO_CODE_3,
	D_REPORT_0,
	D_REPORT_1,
	D_REPORT_2,
	D_REPORT_3,
	D_MAKEGUN_0,
	D_FAMILY_FUNC_0,
	D_FAMILY_FUNC_1,
	D_FAMILY_FUNC_2,
	D_FAMILY_FUNC_3,
	D_FAMILY_FUNC_4,
	D_FAMILY_FUNC_5,
	D_FAMILY_FUNC_6,
	D_FAMILY_FUNC_7,
	D_FAMILY_FUNC_8,
	D_FAMILY_FUNC_9,
	D_FAMILY_FUNC_10,
	D_FAMILY_FUNC_11,
	D_FAMILY_FUNC_12,
	D_FAMILY_FUNC_13,
	D_FAMILY_FUNC_14,
	D_FAMILY_FUNC_15,
	D_FAMILY_FUNC_16,
	D_FAMILY_FUNC_17,
	D_FAMILY_FUNC_18, 
	D_FAMILY_FUNC_19,
	D_FAMILY_FUNC_20,
	D_FAMILY_FUNC_21,
	D_FAMILY_FUNC_22,
	D_FAMILY_FUNC_23,
	D_FAMILY_FUNC_24,
	D_FAMILY_FUNC_25,
	D_FAMILY_FUNC_26,
	D_FAMILY_FUNC_27,
	D_FAMILY_FUNC_28,
	D_FAMILY_FUNC_29,
	D_FAMILY_FUNC_30,
	D_FAMILY_FUNC_31,
	D_FAMILY_FUNC_32,
	D_FAMILY_FUNC_33,
	D_FAMILY_FUNC_34,
	D_FAMILY_FUNC_35,
	D_FAMILY_FUNC_36,
	D_FAMILY_FUNC_37,
	D_FAMILY_FUNC_38,
	D_FAMILY_FUNC_39,
	D_FAMILY_FUNC_40,
	D_FAMILY_FUNC_41,
	D_FAMILY_FUNC_42, 
	D_FAMILY_FUNC_43,
	D_FAMILY_FUNC_44,
	D_FAMILY_FUNC_45,
	D_FAMILY_FUNC_46,
	D_FAMILY_FUNC_47,
	D_FAMILY_FUNC_48,
	D_FAMILY_FUNC_49,
	D_FAMILY_FUNC_50,
	D_FAMILY_FUNC_51,
	D_FAMILY_FUNC_52,
	D_FAMILY_FUNC_53,
	D_FAMILY_FUNC_54,
	D_FAMILY_FUNC_55,
	D_FAMILY_FUNC_56,
	D_FAMILY_FUNC_57,
	D_FAMILY_FUNC_58,
	D_FAMILY_FUNC_59,
	D_FAMILY_FUNC_60,
	D_FAMILY_FUNC_61,
	D_FAMILY_FUNC_62,
	D_FAMILY_FUNC_63,	

	D_TRENER_TEST,

	D_CHANGE_SKIN_BUSINESS_0,	
	D_SELECT_SUSPECT,
	D_LIST_SUSPECT,
	D_ADD_SUSPECT,
	D_GIVE_SUSPECT,
	D_EDIT_SUSPECT_LEVEL,
	D_EDIT_SUSPECT_REASON,
	D_FRACTION_WAREHOUSE,
	// D_FRACTION_L_PANEL,
	D_FRACTION_FUNC_0,
	D_FRACTION_FUNC_1,
	D_FRACTION_FUNC_2,
	D_FRACTION_FUNC_3,
	D_FRACTION_FUNC_4,
	D_FRACTION_FUNC_5,
	D_FRACTION_FUNC_6,
	D_FRACTION_FUNC_7,
	D_FRACTION_FUNC_8,
	D_FRACTION_FUNC_9,
	D_FRACTION_FUNC_10,
	D_FRACTION_FUNC_11,
	D_FRACTION_FUNC_12,
	D_FRACTION_FUNC_13,
	D_FRACTION_FUNC_14,
	D_FRACTION_FUNC_15,
	D_FRACTION_FUNC_16,
	D_FRACTION_FUNC_17,
	D_FRACTION_FUNC_18,
	D_FRACTION_FUNC_19,// Добавить в черны список
	D_FRACTION_FUNC_20,//Очистить черный список
	D_FRACTION_FUNC_21,//Полный список
	D_FRACTION_FUNC_22,//Sklad
	D_FRACTION_FUNC_23,
	D_FRACTION_FUNC_24,
	D_FRACTION_FUNC_25,
	D_FRACTION_FUNC_26,
	D_FRACTION_FUNC_27,
	D_FRACTION_FUNC_28,
	D_FRACTION_FUNC_29,
	D_FRACTION_FUNC_30,
	D_FRACTION_FUNC_31,//select car
	D_FRACTION_FUNC_32,//Buy car
	D_FRACTION_FUNC_33,//Economy
	D_FRACTION_FUNC_34,
	D_FRACTION_FUNC_35,
	D_FRACTION_FUNC_36,
	D_FRACTION_FUNC_37,
	D_FRACTION_FUNC_38,
	D_FRACTION_FUNC_39,
	D_FRACTION_FUNC_40,
	D_FRACTION_FUNC_41,//Изменить ранг на доступ к ТС
	D_FRACTION_FUNC_42,//Изменить ранг на доступ к ТС
	D_FRACTION_FUNC_43,
	D_FRACTION_FUNC_44,
	D_FRACTION_FUNC_45,
	D_FRACTION_FUNC_46,
	D_FRACTION_FUNC_47,
	D_FRACTION_FUNC_48,
	D_FRACTION_FUNC_50,
	D_DIPLOMATION,
	D_DIPLOMATION_2,
	D_FRACTION_FUNC_SALARY, //
	D_FRACTION_FUNC_SELECT, //
	D_FRACTION_FUNC_EDIT, //
	D_FRACTION_FUNC_FORMULE, //
	D_VACANCY_0,
	D_VACANCY_1,
	D_VACANCY_2,
	D_AUTOMARKET,
	DIALOG_ANTICHEAT_SETTINGS,
	DIALOG_ANTICHEAT_EDIT_CODE,//482

	D_STALL_MENU,
	D_HOSPITAL_MENU, //484
	D_HOSPITAL_MENU_0,
	D_BUSINESS_PANEL_MAIN,
	D_BUSINESS_PANEL_INFO,
	D_BUSINESS_PANEL_MESSAGE,
	D_BUSINESS_PANEL_PRICE_LIST,
	D_BUSINESS_PANEL_PRICE_SET,
	D_BUSINESS_PANEL_PROD_MENU,
	D_BUSINESS_PANEL_PROD_INFO,
	D_BUSINESS_PANEL_PROD_BACK,
	D_BUSINESS_PANEL_PROD_ORDER,
	D_BUSINESS_PANEL_SELL,
	D_BUSINESS_PANEL_SELECT,
	D_BUSINESS_PANEL_HISTORY_TRADE,//496
	//
	D_BUSINESS_PANEL_SELECT_SELL,
	D_BUSINESS_PANEL_CONFIRM_SELL,
	D_BUSINESS_SELLBIZ_CONFIRM,//499
	//
	D_BUSINESS_PANEL_SELECT_BIZINFO, //showbizinfo
//	D_BUSINESS_PANEL_CONFIRM_BIZINFO, // select biz - > Show target
	D_BUSINESS_PANEL_SHOW_BIZINFO,
	//
	D_BUSINESS_PANEL_BANK,
	D_BUSINESS_PANEL_BANK_DEPOSIT,
	D_BUSINESS_PANEL_BANK_WITHDRAW,
	D_BUSINESS_PANEL_BANK_LANDTAX,
	D_BUSINESS_PANEL_SELECT_BANK,//504
	//
	D_BUSINESS_PANEL_ENTER_PRICE,
	D_BUSINESS_ENTER,
	D_BUSINESS_BUY_CONFIRM,//507
	//
	D_BUSINESS_BUY_MENU,
	//
	D_BUSINESS_ADD_BIZ_TYPE,
	D_BUSINESS_ADD_BIZ_PRICE,//510
	//
	D_BUSINESS_EDIT_MENU,
	D_BUSINESS_EDIT_NAME,
	D_BUSINESS_EDIT_PRICE,
	D_BUSINESS_EDIT_INTERIOR_ID,
	D_BUSINESS_EDIT_TYPE,
	D_BUSINESS_EDIT_DELETE, 
	D_BUSINESS_BUY_LIST,
	D_BUSINESS_BUY_SIM, 
	D_BUSINESS_ORDERS_MENU,
	D_BUSINESS_ORDERS_LIST,
	D_BUSINESS_ORDERS_LIST_GAS, 
	D_DUEL_LIST,
	D_DUEL_SELECT,
	D_DUEL_SELECT_TEAM,
	D_DUEL_EDIT,
	D_DUEL_CREATE_TYPE,
	D_DUEL_CREATE_BET,
	D_DUEL_CREATE_PASSWORD,
	D_DUEL_CREATE_WEAPON,
	D_DUEL_CREATE_CONFIRM, 
	D_DM_ARENA_0,
	D_DM_ARENA_1,
	D_DM_ARENA_2,
	D_DM_ARENA_3, 
	D_ITEMS_PLAYER, 
	D_ITEMS_USE,
	D_BUSINESS_LIST_CLOTHES,
	D_ITEMS_BUY,
	D_ITEMS_BUY_,
	D_ITEMS_BUY_TYPE,
	D_INV,
	D_INV_,
	D_INV_RC,
	D_INV_INFO,
	D_INV_RENT_STALL,
	D_INV_ADD_STALL_ITEMS,
	D_INV_ADD_STALL_ITEMS_0,
	D_INV_ADD_STALL_ITEMS_1,
	D_INV_ADD_STALL_ITEMS_2,
	D_INV_UNADD_STALL_ITEMS,
	D_INV_UNRENT_STALL_0,
	D_CHANGE_STAR_0,//551 
	D_CHANGE_STAR_1,
	D_CHANGE_STAR_2,
	D_CHANGE_STAR_3,
	D_CHANGE_STAR_4,
	D_CHANGE_STAR_5,
	D_ACTOR_PASS,
	D_ACTOR_PASS_0,
	D_CASINO_ROULETTE_EXIT,
	D_CASINO_ROULETTE_BET, 
	DIALOG_CASINO,
	DIALOG_BJ_TUTORIAL,
	DIALOG_POKER_TUTORIAL,
	DIALOG_CASINO_CHIPS,
	DIALOG_CASINO_BUY_DICE,
	DIALOG_CASINO_BUY_CHIPS,
	DIALOG_CASINO_SELL_CHIPS,
	DIALOG_CASINO_DICE_1,
	DIALOG_CASINO_DICE_2,
	DIALOG_CASINO_LANGUAGE,
	DIALOG_POKER_LEAVE,
	DIALOG_POKER_BET,
	DIALOG_POKER_CALL,
	DIALOG_POKER_RAISE,
	DIALOG_BLACKJACK_BET,
	DIALOG_BLACKJACK_LEAVE,
	D_CONFIRM_DEAL,
	D_STATUS_DEAL,
	D_STATUS_DEAL2,//574
	// /quest
	D_QUEST_0,
	D_QUEST_1,
	D_QUEST_2,
	D_QUEST_3,
	D_QUEST_4,
	D_QUEST_5,
	D_QUEST_6,
	D_QUEST_7,

	D_THEFT_CAR_0,
	D_THEFT_CAR_1,
	D_THEFT_CAR_2,
	D_ROB_HOUSE_0,
	D_ROB_HOUSE_1,
	
	D_AC_SETTINGS,
	D_AC_SETTINGS2,
	D_AC_SETTINGS3,
	D_AC_SETTINGS4,
	D_AC_SETTINGS5,
	D_AC_SETTINGS6,
	D_AC_SETTINGS7,
	D_AC_SETTINGS8,
	D_AC_SETTINGS9,
	D_AC_SETTINGS10,
	D_AC_SETTINGS11,
	D_AC_SETTINGS12,
	D_AC_SETTINGS13,

	D_ACHIV_MENU,
	D_ACHIV_RETURN_MENU,

	D_CAM_LIST,

	D_TEMPLEADER,
	D_ANTICHEAT, 
	D_PLAYER_TATGET_0,
	D_PLAYER_TATGET_1,
	D_PLAYER_TATGET_2,
	D_PLAYER_TATGET_3,
	D_PLAYER_TATGET_4,
	D_PLAYER_TATGET_5,	

	D_BIKER_FUNC_0,
	D_BIKER_FUNC_1,
	D_BIKER_FUNC_2,
	D_BIKER_FUNC_3,
	D_BIKER_FUNC_4,
	D_BIKER_FUNC_5,
	D_BIKER_FUNC_6,
	D_BIKER_FUNC_7,
	D_BIKER_FUNC_8,
	D_BIKER_FUNC_9,
	D_BIKER_FUNC_10,
	D_BIKER_FUNC_11,
	D_BIKER_FUNC_12,
	D_BIKER_FUNC_13,
	D_BIKER_FUNC_14,
	D_BIKER_FUNC_15,
	D_BIKER_FUNC_16,
	D_TRUCKER_BUY,
	D_PLAYER_HOTDOG,
	D_PLAYER_HOTDOG_JOB,
	D_PLAYER_HOTDOG_SELLER,
	D_PLAYER_HOTDOG_CONTRACT,
	D_PROMO_CODE_REFERAL_0,
    D_PROMO_CODE_REFERAL_1, // return Main Menu
    D_PROMO_CODE_REFERAL_2,
    D_PROMO_CODE_REFERAL_3,
	D_PROMO_CODE_REFERAL_4,
	D_PROMO_CODE_REFERAL_5,
	D_PROMO_CODE_REFERAL_6,
	D_PROMO_CODE_REFERAL_7,
	D_PROMO_CODE_REFERAL_8,
	D_PROMO_CODE_REFERAL_9,
	D_PROMO_CODE_REFERAL_10,
	D_PROMO_CODE_REFERAL_11,
	D_PROMO_CODE_REFERAL_12,
	D_PAME,
	D_EU_1,
	D_EU_2,
	D_EU_3,
	D_PRIZE_OPEN,
	D_PLAYER_HUNTER_0,
	D_PLAYER_HUNTER_1,
	D_INTERACTION,
	D_CONT_1,
	D_CONT_2,
	D_CONT_3,
	D_CONVERTMONEY,
	D_UNPRISON
} 

// * Типы уведомлений
enum E_NOTIFY_TYPE
{
    SUCCESS,
    ERROR
}; 
