; Основные настройки проекта
server_name = BLESS KAZAKHSTAN

; Стартовый бонус
bonus_money = 35000000
bonus_donate = 500
bonus_lvl = 1
vip = 0

; Музыка при входе (прямая ссылка на MP3)
; Можно также использовать ключ join_music_url

; Сообщение команды /cc
; Можно также использовать ключ clear_chat_message
cc_message = {FF0000}Чат был очищен администратором

; Прочие настройки
whitelist = 0
nameserver = BLESS KAZAKHSTAN
audio_url = https://eu.hitmoz.com/get/music/20260202/Junior_-_VAT_IZ_LAV_80764814.mp3
