# Настройки проекта LAIRD
# После изменения перезапустите сервер.

donate = 10000
money = 45000000
vip = 3
lvl = 3

nameserver = BLUE KAZAHSTAN
tg = t.me/legacyussia
vk = vk.com/legacy
site = legacy.com

whitelist = смотри файл whitelist.ini
full_access_name = Owner_Name

audio_url = http://example.com/menu.mp3
chat = {FFCD00}Чат был очищен администрацией
