static const Float:autoschool_route_car[][] = {
	{-581.8495,90.3978,13.4216}, 
	{-506.3744,103.6150,13.4290}, 
	{-396.8290,104.0234,13.4380}, 
	{-372.1385,129.4331,13.4510}, 
	{-352.7778,289.3125,12.7654}, 
	{-316.8143,583.3611,11.7105}, 
	{-286.0585,593.1648,11.7104}, 
	{-52.5836,568.7083,11.7057}, 
	{100.2768,541.8506,11.7049}, 
	{134.2037,561.2477,11.7055}, 
	{197.0384,725.1336,11.7057}, 
	{247.0144,854.0784,11.7066}, 
	{288.4499,1098.6952,11.7057}, 
	{304.0251,1249.2727,11.6014}, 
	{329.8723,1531.2860,11.7100}, 
	{337.4879,1660.5420,11.7044}, 
	{312.2174,1689.7723,11.7040}, 
	{183.8430,1639.4810,11.7036}, 
	{111.0239,1282.5811,11.7056}, 
	{15.5170,894.5490,11.7076}, 
	{-24.9077,898.4291,11.6997}, 
	{-265.8590,978.1505,11.7057}, 
	{-363.3327,973.5953,11.7147}, 
	{-385.1783,940.0962,11.7130}, 
	{-406.4407,931.8882,11.7180}, 
	{-422.7606,925.1081,11.6929}, 
	{-391.6758,905.5745,11.7076}, 
	{-385.5586,873.2709,11.7057}, 
	{-381.4742,627.3453,11.7077}, 
	{-366.7034,605.2938,11.7100}, 
	{-339.4811,601.1334,11.7107}, 
	{-331.2868,569.2626,11.9624}, 
	{-372.9601,215.7376,13.0777}, 
	{-386.6784,119.0456,13.4541}, 
	{-413.4085,110.8178,13.4289}, 
	{-570.5845,109.8444,13.4249}, 
	{-588.2090,76.6735,13.4210},
	{-584.3361,32.7166,12.8776},
	{-538.2565,20.2537,12.8804},
	{0.0, 0.0, 0.0}

};

static const Float:autoschool_route_boat[][] = {
	{-583.9983,-107.3143,-0.5695}, 
	{-771.4872,-159.1926,-0.5060}, 
	{-939.3611,-195.2091,-0.5597}, 
	{-1020.8622,-322.0674,-0.5859}, 
	{-953.0834,-416.1925,-0.5361}, 
	{-871.5411,-441.4320,-0.5725}, 
	{-730.1395,-429.1268,-0.6318}, 
	{-517.4018,-398.1479,-0.5936}, 
	{-175.5287,-351.8622,-0.6099}, 
	{224.3704,-308.2193,-0.5780}, 
	{430.4927,-212.4122,-0.6025}, 
	{759.2115,-171.3282,-0.5355}, 
	{1060.1169,-105.4423,-0.5011}, 
	{1356.4342,-21.7686,-0.5430}, 
	{1555.5291,20.0981,-0.5449}, 
	{1833.3475,72.5817,-0.6579}, 
	{2085.4814,109.7370,-0.5380}, 
	{2163.3164,155.8861,-0.6075}, 
	{2088.1567,199.3128,-0.5335}, 
	{1939.1025,216.5937,-0.5285}, 
	{1693.9219,209.8570,-0.4556}, 
	{1452.5107,201.5061,-0.3861}, 
	{1231.5105,177.9164,-0.5125}, 
	{945.6511,81.8676,-0.4524}, 
	{636.4131,-32.8734,-0.5284}, 
	{375.3986,-143.8978,-0.4329}, 
	{173.0239,-178.6543,-0.4757}, 
	{-51.7702,-194.0854,-0.4929}, 
	{-200.5337,-203.4606,-0.4887}, 
	{-349.1738,-167.3050,-0.4722}, 
	{-459.2369,-79.6861,-0.6490},
	{0.0, 0.0, 0.0}
};

static const Float:autoschool_route_fly[][] = {
	{-469.2853,35.4493,151.6918},
	{-371.3699,-56.7344,177.9328},
	{-164.4028,-111.6908,196.2226},
	{145.8562,-3.2568,187.6162},
	{286.4219,200.1563,190.8819},
	{413.9194,617.9406,200.1490},
	{478.1010,1099.8098,244.9840},
	{472.4751,1454.2032,230.3774},
	{478.7308,1699.8287,197.0191},
	{343.5819,1968.9271,226.0240},
	{120.9016,1798.9697,246.3311},
	{26.7990,1528.8806,239.2706},
	{-211.8032,1171.2236,185.2307},
	{-451.6112,1185.5396,207.1970},
	{-692.0306,1327.9728,211.4704},
	{-1041.6750,1475.8638,218.0039},
	{-1374.2616,1548.4895,193.4628},
	{-1329.7979,1432.9648,218.0527},
	{-1109.7373,1158.2242,203.0572},
	{-824.8907,739.7468,189.8522},
	{-661.4006,333.4031,169.6732},
	{-563.9731,122.7198,120.7024},
	{-468.1022,68.3840,39.9017},
	{-447.0049,39.4313,14.9224},
	{0.0, 0.0, 0.0}
};

static const Float:autoschool_exam_coord[][] = {

	{12.8303,-12.5091,1731.1689,213.5433},
	{15.4472,-11.1056,1731.1566,215.1315},
	{27.0234,-6.2682,1731.1455,211.9890},
	{24.2741,-7.6047,1731.1455,212.3364},
	{21.3406,-8.7708,1731.1455,214.0239},
	{18.3474,-9.8392,1731.1455,217.7464},
	{15.8286,-17.7165,1731.1455,265.3439},
	{18.9875,-17.1261,1731.1455,262.6637},
	{21.8527,-16.6871,1731.1455,263.1104},
	{24.8917,-15.1621,1731.1455,262.7629},
	{27.7739,-13.3478,1731.1455,259.0901},
	{30.3507,-11.4308,1731.1455,261.7703}

};

stock get_lic_price(i, type)
{
	switch(type)
	{
		case 1:
		{
			if(pData[i][pLevel] < 3) 
				return 1000;

			else if(3 < pData[i][pLevel] < 7) 
				return 2500;

			else return 5000;
		}
		case 2:
		{
			if(pData[i][pLevel] < 3) 
				return 1500;
			else if(3 < pData[i][pLevel] < 7) 
				return 5000;

			else return 10000;
		}
		case 3:
		{
			if(pData[i][pLevel] < 3) 
				return 5000;

			else if(3 < pData[i][pLevel] < 7) 
				return 15000;

			else return 30000;
		}
	}
	return true;
}

stock create_autoschool_pickups()
{
	as_pick_car = create_circle_pickup(11.3445,-18.4520,1731.1455, TRIGGER_LBLUE);

	as_pick_boat = create_circle_pickup(-447.4454,-48.1299,2.7685, TRIGGER_LBLUE);

	as_pick_fly = create_circle_pickup(-559.3868,38.0641,13.7661, TRIGGER_LBLUE);

	as_pick_car_rent = create_circle_pickup(-521.4979,22.0371,13.7192, TRIGGER_LBLUE);

	as_actor[0] = CreateActor(17, 9.6913,-18.3294,1731.1455,266.0052);
	SetActorVirtualWorld(as_actor[0], 10);

	as_actor[1] = CreateActor(36, -446.6998,-48.9845,2.7685,40.8547);

	as_actor[2] = CreateActor(61, -560.0300,37.1931,13.7661,321.8398); //NPC-Пилот

	as_actor[3] = CreateActor(185, -520.7220,22.9250,13.7192,129.2644);

	as_actor[4] = CreateActor(17, -1.6793,12.8302,1731.2002,125.5629);
	SetActorVirtualWorld(as_actor[4], 10);

	as_pick_info = create_circle_pickup(-1.3310,10.5428,1731.2002, TRIGGER_LBLUE);

	CreateDynamic3DTextLabel("\t\t"cBLUE"Пилот-Инструктор\n"cWH"Александр Козлов", -1, -560.0300,37.1931,13.7661+0.3, 5.0);  
	CreateDynamic3DTextLabel("\t\t"cBLUE"Капитан-Инструктор\n"cWH"Константин Маркин", -1, -446.6998,-48.9845,2.7685+0.3, 5.0);  
	CreateDynamic3DTextLabel("\t\t"cBLUE"Инструктор\n"cWH"Егор Тихонов", -1, 9.6913,-18.3294,1731.1455+0.3, 5.0);  
	CreateDynamic3DTextLabel("\t\t"cBLUE"Инструктор\n"cWH"Пётр Степанов", -1, -520.7220,22.9250,13.7192+0.3, 5.0);  


	for(new i; i < sizeof(autoschool_exam_coord); i++)
	{
		as_tables[i] = create_circle_pickup(autoschool_exam_coord[i][0], autoschool_exam_coord[i][1], autoschool_exam_coord[i][2], TRIGGER_LBLUE);

		CreateDynamic3DTextLabel(""cWH"Стол для сдачи\n"cBLUE"Экзамен и изучение",-1, \
		autoschool_exam_coord[i][0], autoschool_exam_coord[i][1], autoschool_exam_coord[i][2], 2.0, INVALID_PLAYER_ID, INVALID_VEHICLE_ID, 10, -1);	
	}

	return true;
}

stock close_info_exam_all(playerid)
{
	TextDrawHideForPlayer(playerid, autoschool_info_td[0]);
	TextDrawHideForPlayer(playerid, autoschool_info_td[1]);
	TextDrawHideForPlayer(playerid, autoschool_info_td[2]);
	TextDrawHideForPlayer(playerid, autoschool_info_td[3]);
	TextDrawHideForPlayer(playerid, autoschool_info_td[4]);
	TextDrawHideForPlayer(playerid, autoschool_info_td[5]);
	TextDrawHideForPlayer(playerid, autoschool_info_td[6]);


	TextDrawHideForPlayer(playerid, autoschool_info_td_1[0]);
	TextDrawHideForPlayer(playerid, autoschool_info_td_1[1]);
	TextDrawHideForPlayer(playerid, autoschool_info_td_2[0]);
	TextDrawHideForPlayer(playerid, autoschool_info_td_2[1]);
	TextDrawHideForPlayer(playerid, autoschool_info_td_3[0]);
	TextDrawHideForPlayer(playerid, autoschool_info_td_3[1]);

	CancelSelectTextDraw(playerid);

	return true;
}

stock show_select_autoschool_exam(playerid)
{
	TextDrawShowForPlayer(playerid, autoschool_info_td[0]);
	TextDrawShowForPlayer(playerid, autoschool_info_td[1]);
	TextDrawShowForPlayer(playerid, autoschool_info_td[2]);
	TextDrawShowForPlayer(playerid, autoschool_info_td[3]);
	TextDrawShowForPlayer(playerid, autoschool_info_td[4]);
	TextDrawShowForPlayer(playerid, autoschool_info_td[5]);
	TextDrawShowForPlayer(playerid, autoschool_info_td[6]);

	SelectTextDraw(playerid, COLOR_BLUE);

	return true;
}

stock hide_select_autoschool_exam(playerid)
{
	TextDrawHideForPlayer(playerid, autoschool_info_td[0]);
	TextDrawHideForPlayer(playerid, autoschool_info_td[1]);
	TextDrawHideForPlayer(playerid, autoschool_info_td[2]);
	TextDrawHideForPlayer(playerid, autoschool_info_td[3]);
	TextDrawHideForPlayer(playerid, autoschool_info_td[4]);
	TextDrawHideForPlayer(playerid, autoschool_info_td[5]);
	TextDrawHideForPlayer(playerid, autoschool_info_td[6]);

	CancelSelectTextDraw(playerid);

	return true;	
}

stock show_info_exam_auto(playerid)
{
	if(pData[playerid][pLicenses][LIC_DRIVING]) 
	{
		SelectTextDraw(playerid, COLOR_BLUE);
		return SendErr(playerid, "У Вас уже имеются водительские права");
	}

	TextDrawHideForPlayer(playerid, autoschool_info_td[0]);
	TextDrawHideForPlayer(playerid, autoschool_info_td[1]);
	TextDrawHideForPlayer(playerid, autoschool_info_td[2]);
	TextDrawHideForPlayer(playerid, autoschool_info_td[3]);
	TextDrawHideForPlayer(playerid, autoschool_info_td[4]);
	TextDrawHideForPlayer(playerid, autoschool_info_td[5]);
	TextDrawHideForPlayer(playerid, autoschool_info_td[6]);


	TextDrawShowForPlayer(playerid, autoschool_info_td_1[0]);
	TextDrawShowForPlayer(playerid, autoschool_info_td_1[1]);

	SelectTextDraw(playerid, COLOR_BLUE);

	return true;	
}

stock show_info_exam_vert(playerid)
{
	if(pData[playerid][pLicenses][LIC_FLY])
	{
		SelectTextDraw(playerid, COLOR_BLUE);
		return SendErr(playerid, "У Вас имеется лицензия для воздушного транспорта");
	}


	TextDrawHideForPlayer(playerid, autoschool_info_td[0]);
	TextDrawHideForPlayer(playerid, autoschool_info_td[1]);
	TextDrawHideForPlayer(playerid, autoschool_info_td[2]);
	TextDrawHideForPlayer(playerid, autoschool_info_td[3]);
	TextDrawHideForPlayer(playerid, autoschool_info_td[4]);
	TextDrawHideForPlayer(playerid, autoschool_info_td[5]);
	TextDrawHideForPlayer(playerid, autoschool_info_td[6]);


	TextDrawShowForPlayer(playerid, autoschool_info_td_2[0]);
	TextDrawShowForPlayer(playerid, autoschool_info_td_2[1]);

	SelectTextDraw(playerid, COLOR_BLUE);

	SetPlayerCheckpoint(playerid, -560.0300,37.1931,13.7661, WOOD_CHECKPOINT_SIZE);
	SendInf(playerid, "Отправляйтесь на вертолетную площадку возле Автошколы и пройдите экзамен на управление воздушным транспортом!");
	return true;	
}

stock show_info_exam_aqua(playerid)
{

	if(pData[playerid][pLicenses][LIC_BOAT]) 
	{
		SelectTextDraw(playerid, COLOR_BLUE);
		return SendErr(playerid, "У Вас имеется лицензия для водного транспорта");
	}

	TextDrawHideForPlayer(playerid, autoschool_info_td[0]);
	TextDrawHideForPlayer(playerid, autoschool_info_td[1]);
	TextDrawHideForPlayer(playerid, autoschool_info_td[2]);
	TextDrawHideForPlayer(playerid, autoschool_info_td[3]);
	TextDrawHideForPlayer(playerid, autoschool_info_td[4]);
	TextDrawHideForPlayer(playerid, autoschool_info_td[5]);
	TextDrawHideForPlayer(playerid, autoschool_info_td[6]);


	TextDrawShowForPlayer(playerid, autoschool_info_td_3[0]);
	TextDrawShowForPlayer(playerid, autoschool_info_td_3[1]);

	SelectTextDraw(playerid, COLOR_BLUE);

	SetPlayerCheckpoint(playerid, -446.6998,-48.9845,2.7685, WOOD_CHECKPOINT_SIZE);
	SendInf(playerid, "Отправляйтесь на пирс возле Автошколы и пройдите экзамен на управление водным транспортом!");
	return true;	
}

static const school_test_active_dialog[][ENUM_AUTO_SCHOOL_TEST] =
{
	{
		"\
		"cBLUE"Теоретический тест\n\n\
		"cBLUE"-"cWH" При движении по двухполосной дороге за грузовым автомобилем\n\
		у Вас появилась возможность совершить обгон. Ваши действия?",
		"Какие действия?", "Поеду по обочине", "Не буду совершать обгон", "Перестроюсь на встречную полосу и завершу маневр",
  		4
	},
	{
		"\
		"cBLUE"Теоретический тест\n\n\
		"cBLUE"-"cWH" В тоннеле с искусственным освещением должны быть включены:",
		"Фары ближнего света или габаритные огни", "Фары ближнего света", "Прожектор", "Фары ближнего и дальнего света",
  		4
	},
	{
		"\
		"cBLUE"Теоретический тест\n\n\
		"cBLUE"-"cWH" Когда следует включать указатели поворота?",
		"Непосредственно перед поворотом или разворотом", "Заблаговременно до начала маневра", "По усмотрению водителя", "Я на BMW, у нас так не принято",
  		2
	},
	{
		"\
		"cBLUE"Теоретический тест\n\n\
		"cBLUE"-"cWH" Чем необходимо руководствоваться, если нанесенные на проезжей части белые\n\
		и оранжевые линии разметки противоречат друг другу?",
		"Оранжевым линиям", "Белым линиям", "Я не смотрю на разметку", "В правилах такого нет",
  		1
	},
	{
		"\
		"cBLUE"Теоретический тест\n\n\
		"cBLUE"-"cWH" Разрешается ли устанавливать на транспортном средстве \n\
		ошипованные шины совместно с неошипованными?",
		"Только на разные оси", "Запрещается", "Если никто не видит", "В правилах такого нет",
  		2
	},
	{
		"\
		"cBLUE"Теоретический тест\n\n\
		"cBLUE"-"cWH" Исключает ли антиблокировочная тормозная система возможность\n\
		возникновения заноса или сноса при прохождении поворота?",
		"Полностью исклучает возникновение заноса", "Полностью исклучает возникновение сноса", "Не исключает", "Исключает оба варианта",
  		3
	},
	{
		"\
		"cBLUE"Теоретический тест\n\n\
		"cBLUE"-"cWH" Как необходимо обозначить буксируемый автомобиль\n\
		при отсутствии или неисправности аварийной сигнализации?",
		"Установить на задней части автомобиля знак аварийной остановки", "Включить габаритные огни", "Включить противотуманные фонари", "Никак",
  		1
	},
	{
		"\
		"cBLUE"Теоретический тест\n\n\
		"cBLUE"-"cWH" Должны ли Вы переключить дальний свет на ближний, \n\
		если водитель встречного транспортного средства периодическим \n\
		переключением света фар покажет необходимость этого?",
		"Обязан", "Не обязан, его проблемы", "Если расстояние менее 150 м", "Обязан во всех случаях",
  		1
	},
	{
		"\
		"cBLUE"Теоретический тест\n\n\
		"cBLUE"-"cWH" Водитель обгоняемого транспортного средства:",
		"Обязан снизить скорость", "Обязан не повышать скорость", "На своё усмотрение", "Ничего не обязан",
  		2
	},
	{
		"\
		"cBLUE"Теоретический тест\n\n\
		"cBLUE"-"cWH" Максимальная скорость движения в городе?",
		"90 км/ч", "40 км/ч", "50 км/ч", "60 км/ч",
  		4
	}
};





stock dialog_autoschool_dialog_lic(playerid, type)
{
	if(GetPVarIntNew(playerid, "autoschool_type")) 
		return SendErr(playerid, "Вы уже начали сдачу практической части экзамена");

	switch(type)
	{
		case AS_CAR:
		{
			if(pData[playerid][pLicenses][LIC_DRIVING]) 
				return SendErr(playerid, "У Вас уже имеются водительские права");

			return SPD(playerid, DIALOG_AUTOSCHOOL_CAR_ACTOR_HI, DIALOG_STYLE_MSGBOX, !""cBLUE"Водительские права", !"\
				"cWH"Добро пожаловать в автошколу Арзамас\n\n\
				Перед началом сдачи экзамена в Автошколе, советуем изучить ПДД\n\
				ПДД - Важная база знаний при вождение транспортных средств\n\
				Если не знать ПДД, то можно допустить можно ошибок и в самом легком случае\n\
				отделаться штрафом, а если не повезет, то и в ДТП попасть!\n\n\
				"cWH"Готовы приступить?", !"Изучить", !"Экзамен");
		}
		case AS_BOAT:
		{
			if(pData[playerid][pLicenses][LIC_BOAT]) 
				return SendErr(playerid, "У Вас имеется лицензия для водного транспорта");

			static tmp_string[550];

			format(tmp_string, 550, "\
			"cWH"Добро пожаловать в водную школу Арзамаса\n\n\
			Хотите научиться управлять водным транспортом?\n\
			Здесь мы научим Вас управлять водным транспортом легко и просто!\n\
			Купить свою лодку и направиться на рыбалку или же просто кататься по рекам!\n\n\
			Стоимость практики и получения лицензии: "cGR"%d рублей\n\
			"cWH"Готовы приступить?", get_lic_price(playerid, AS_BOAT));
			
			SPD(playerid, DIALOG_AUTOSCHOOL_BOAT, DIALOG_STYLE_MSGBOX, !""cBLUE"Права на водный транспорт", tmp_string, !"Да", !"Нет");

			tmp_string[0] = EOS;
			return true;
		}
		case AS_FLY:
		{
			if(pData[playerid][pLicenses][LIC_FLY])
				return SendErr(playerid, "У Вас имеется лицензия для воздушного транспорта");

			new 
				tmp_string[500];


			format(tmp_string, 500, "\
			"cWH"Добро пожаловать в летную школу Арзамаса, как Вам у нас?\n\n\
			Как же прекрасно пролететь на своём вертолете возле Москвы-Сити?\n\
			Я тоже думаю, что круто, но для этого нужна лицензия на полеты!\n\
			Вертолет - это не шутка, поэтому я Вас научу всему тому, что знаю сам!\n\n\
			Так что нужно научиться летать на вертолете и Вы получите лицензию\n\
			Стоимость практики и получения лицензии пилота: "cGR"%d рублей""\n\
			"cWH"Готовы приступить?", get_lic_price(playerid, AS_FLY));

			return SPD(playerid, DIALOG_AUTOSCHOOL_FLY, DIALOG_STYLE_MSGBOX, !""cBLUE"Лицензия на воздушный транспорт", tmp_string, !"Да", !"Нет");
		}
	}
	return true;
}
stock dialog_autoschool_exam(playerid)
{
	static
		tmp_string[500];

	format(tmp_string, 500, "\
		"cWH"Перед началом сдачи советуем вам изучить внимательно ПДД\n\
		Каждая неудачная попытка будет стоить Вам денег, поэтому будьте внимательны\n\n\
		Стоимость получения лицензии: "cGR"%d рублей", get_lic_price(playerid, AS_CAR));

	SPD(playerid, DIALOG_AUTOSCHOOL_CAR_START, DIALOG_STYLE_MSGBOX, !""cBLUE"Водительские права", tmp_string, !"Да", !"Нет");
	tmp_string[0] = EOS;
	return true;
}

stock dialog_autoschool(playerid, dialogid, response, inputtext[])
{
	switch(dialogid)
    {
		case DIALOG_AUTOSCHOOL_CAR_EXAM:
		{
			if(response)
				return SPD(playerid, 0, DIALOG_STYLE_MSGBOX, !""cBLUE"Водительские права", !"\
					"cWH"Проходите в аудиторию и приступайте к сдачи теоритической части!", !"Понятно", !"");
			else return SPD(playerid, 0, DIALOG_STYLE_MSGBOX, !""cBLUE"Теоретический экзамен", !"\
		    		"cWH"Будем ждать Вас в следующий раз!", !"Хорошо", !"");
		}
		case DIALOG_AUTOSCHOOL_CAR_ACTOR_HI:
		{
			if(!response) return SPD(playerid, 0, DIALOG_STYLE_MSGBOX, !""cBLUE"Водительские права", !"\
					"cWH"Проходите в аудиторию и приступайте к сдачи теоритической части!", !"Понятно", !"");

			return dialog_autoschool_theory_1(playerid);
		}
		case DIALOG_AUTOSCHOOL_THEORY_1:
		{
			if(!response) 
				return true;

			return dialog_autoschool_theory_2(playerid);
		}
		case DIALOG_AUTOSCHOOL_THEORY_2:
		{
			if(!response) 
				return dialog_autoschool_theory_1(playerid);

			return dialog_autoschool_theory_3(playerid);
		}
		case DIALOG_AUTOSCHOOL_THEORY_3:
		{
			if(!response) 
				return dialog_autoschool_theory_2(playerid);

			return dialog_autoschool_theory_4(playerid);
		}
		case DIALOG_AUTOSCHOOL_THEORY_4:
		{
			if(!response)
				return dialog_autoschool_theory_3(playerid);

			return dialog_autoschool_theory_5(playerid);
		}
		case DIALOG_AUTOSCHOOL_THEORY_5:
		{
			if(!response) 
				return dialog_autoschool_theory_4(playerid);

			return dialog_autoschool_theory_6(playerid);
		}
		case DIALOG_AUTOSCHOOL_THEORY_6:
		{
			if(!response) 
				return dialog_autoschool_theory_5(playerid);

			return dialog_autoschool_theory_7(playerid);
		}
		case DIALOG_AUTOSCHOOL_THEORY_7:
		{
			if(!response) 
				return dialog_autoschool_theory_6(playerid);

			return dialog_autoschool_theory_8(playerid);
		}
		case DIALOG_AUTOSCHOOL_THEORY_8:
		{
			if(!response) 
				return dialog_autoschool_theory_7(playerid);

			return dialog_autoschool_theory_10(playerid);
		}

		case DIALOG_AUTOSCHOOL_BOAT:
		{
			if(!response) 
				return true;

			if(pData[playerid][pLicenses][LIC_BOAT]) 
				return SendErr(playerid, "У Вас уже имеются права на управление водным транспортом");

			if(GetPlayerMoneyEx(playerid) < get_lic_price(playerid, AS_BOAT)) 
			{
				show_notify_gui(playerid, TEXTDRAW_SHOW, NOTIFY_GUI_256_RIGHT, "brilliantother:info_gui_no_money", 3000);
				return SendErr(playerid,"У вас недостаточно денежных средств для оплаты автошколы!");
			}

			give_money(playerid, -get_lic_price(playerid, AS_BOAT), "Лицензия на лодку");


			SetPVarIntNew(playerid, "autoschool_type", AS_BOAT);
			SetPVarIntNew(playerid, "autoschool_route", 0);
			SetPVarIntNew(playerid, "autoschool_time", gettime() + 750);
			DeletePVarNew(playerid, "spawn_veh_exam_school");

			SCM(playerid, -1, "");
			SendInf(playerid, "Вы начали практическую часть экзамена на получение лицензии на управление водным транспортом!");
			SendInf(playerid, "Следуйте по чекпоинтам и пройдите весь маршрут!");
			create_school_exam_boat(playerid);

		}
		case DIALOG_AUTOSCHOOL_FLY:
		{
			if(!response) 
				return true;

			if(pData[playerid][pLicenses][LIC_FLY]) 
				return SendErr(playerid, "У Вас уже имеются права на управление воздушным транспортом");

			if(GetPlayerMoneyEx(playerid) < get_lic_price(playerid, AS_FLY)) 
			{
				show_notify_gui(playerid, TEXTDRAW_SHOW, NOTIFY_GUI_256_RIGHT, "brilliantother:info_gui_no_money", 3000);
				return SendErr(playerid,"У вас недостаточно денежных средств для оплаты автошколы!");
			}

			give_money(playerid, -get_lic_price(playerid, AS_FLY), "Лицензия на полеты");

			SetPVarIntNew(playerid, "autoschool_type", AS_FLY);
			SetPVarIntNew(playerid, "autoschool_route", 0);
			SetPVarIntNew(playerid, "autoschool_time", gettime() + 750);
			DeletePVarNew(playerid, "spawn_veh_exam_school");

			SCM(playerid, -1, "");
			SendInf(playerid, "Вы начали практическую часть экзамена на получение лицензии на управление воздушным транспортом!");
			SendInf(playerid, "Следуйте по чекпоинтам и пройдите весь маршрут!");
			create_school_exam_vert(playerid);

		}
		case DIALOG_AUTOSCHOOL_CAR_START:
		{
		    if(!response)
		    {
		    	DeletePVarNew(playerid, "AH_TEST");
		    	DeletePVarNew(playerid, "AH_TEST_BALANCE");
		    	return true;
		    }

		    if(!GetPVarIntNew(playerid, "AH_TEST"))
		    {
		    	if(pData[playerid][pLicenses][LIC_DRIVING]) 
		    		return SendErr(playerid, "У Вас уже имеются водительские права");

				if(GetPlayerMoneyEx(playerid) < get_lic_price(playerid, AS_CAR)) 
				{
					show_notify_gui(playerid, TEXTDRAW_SHOW, NOTIFY_GUI_256_RIGHT, "brilliantother:info_gui_no_money", 3000);
					return SendErr(playerid,"У вас недостаточно денежных средств для оплаты автошколы!");
				}

		    	SetPVarIntNew(playerid, "AH_TEST", 1);
		    	SetPVarIntNew(playerid, "AH_TEST_BALANCE", 0);
		    	give_money(playerid, -get_lic_price(playerid, AS_CAR), "Лицензия на вождение");
		    }

		    new qID = GetPVarIntNew(playerid, "AH_TEST")-1;
		    static tmpstr[780];
		    if((strlen(inputtext) != 0) && ((strval(inputtext) > 0) && (strval(inputtext) <= 4)))
		    {
		        if(school_test_active_dialog[qID][as_TrueAnsw] == strval(inputtext)) SetPVarIntNew(playerid, "AH_TEST_BALANCE", GetPVarIntNew(playerid, "AH_TEST_BALANCE")+1);
				if(qID+1 >= sizeof(school_test_active_dialog))
				{
				    if(GetPVarIntNew(playerid, "AH_TEST_BALANCE") >= 8)
				    {
						SetPVarIntNew(playerid, "autoschool_type", AS_CAR);
						SetPVarIntNew(playerid, "autoschool_route", 0);
						SetPVarIntNew(playerid, "autoschool_time", gettime() + 900);
						SCM(playerid, -1, "");
						SendInf(playerid, "Вы начали практическую часть экзамена на водительские права");
						SendInf(playerid, "Выйдите на улице, подойдите к Пётру Степанову для получения автомобиля!");

					}
					else 
					{
						SCM(playerid, -1, "");
						SendInf(playerid, "Вы не набрали удовлетворительное количество баллов!");
						SendInf(playerid, "Вам придется пройти теоритическую часть повторно!");
						SendInf(playerid, "Изучите ПДД более подробно, чтобы не допускать ошибок!");
					}

					DeletePVarNew(playerid, "AH_TEST");
					DeletePVarNew(playerid, "AH_TEST_BALANCE");
					return true;
				}
		        qID++;
				SetPVarIntNew(playerid, "AH_TEST", qID+1);
		    }
		    format(tmpstr, sizeof(tmpstr), "\
		    	"cWH"Вопрос "cBLUE"№%d\n\n\
				"cGR"%s\n\n\
				"cBLUE"1. "cWH"%s\n\
				"cBLUE"2. "cWH"%s\n\
				"cBLUE"3. "cWH"%s\n\
				"cBLUE"4. "cWH"%s\n\n\
				Ваш вариант ответа (Введите цифру ответа):",
				qID+1,
				school_test_active_dialog[qID][as_Question],
				school_test_active_dialog[qID][as_Asnw1],
				school_test_active_dialog[qID][as_Asnw2],
				school_test_active_dialog[qID][as_Asnw3],
				school_test_active_dialog[qID][as_Asnw4]);

			SPD(playerid, DIALOG_AUTOSCHOOL_CAR_START, DIALOG_STYLE_INPUT, !""cBLUE"Экзамен по теории", tmpstr, !"Далее", !"");

			tmpstr[0] = EOS;

			return true;
		}
    }
    return true;
}

stock autoschool_route(i, carid, route)
{
	if(vehicle[carid][cOwnTo] != VEHICLES_AUTOSCHOOL) return autoschool_end_lesson(i);
	
	new time = GetTickCount();


	new
		next_route = route + 1;


	switch(GetPVarIntNew(i, "autoschool_type"))
	{
		case 1:
		{

			if(route == sizeof autoschool_route_car - 1)
			{
				new Float:car_health;
				GetVehicleHealth(carid, car_health);

				if(car_health < 900)
				{
					SCM(i, -1, "");
					SendErr(i, "Вы повредили транспортное средство и провалили практический экзамен в автошколе!");

					DestroyVehicle(carid);

					DeletePVarNew(i, "autoschool_type");
					DeletePVarNew(i, "autoschool_route");
					DisablePlayerRaceCheckpoint(i);
				}
				else
				{
					SCM(i, -1, "");
					SendInf(i, "Поздравляем! Вы успешно сдали практический экзамен и получили водительские права!");
					SendInf(i, "Посмотреть свои лицензии можно через команду - /lic");

					pData[i][pLicenses][LIC_DRIVING] = 1;

					check_quest_prize_start(i, 10);
					check_quest_prize_start(i, 7);

					SetPlayerVirtualWorld(i, 0);
					
					UpdatePlayerData(i, "licDrive", 1);

					DestroyVehicle(carid);

					DeletePVarNew(i, "autoschool_type");
					DeletePVarNew(i, "autoschool_route");
					DisablePlayerRaceCheckpoint(i);
				}
			}
			else
			{
				random_phrase_exam_drive_v(i, route);
				SetPlayerRaceCheckpoint(i, 3, autoschool_route_car[route][0], autoschool_route_car[route][1], autoschool_route_car[route][2], autoschool_route_car[next_route][0], autoschool_route_car[next_route][1], autoschool_route_car[next_route][2] - 2.0, 4.0);
			}
		}
		case 2:
		{

			if(route == sizeof autoschool_route_boat - 1)
			{
				new Float:car_health;
				GetVehicleHealth(carid, car_health);
				if(car_health < 900)
				{
					SCM(i, -1, "");
					SendErr(i, "Вы повредили транспортное средство и провалили практический экзамен в автошколе!");

					DestroyVehicle(carid);

					DeletePVarNew(i, "autoschool_type");
					DeletePVarNew(i, "autoschool_route");
					DisablePlayerRaceCheckpoint(i);
				}
				else
				{
					SCM(i, -1, "");
					SendInf(i, "Поздравляем! Вы успешно сдали практический экзамен и получили права на управление водным транспортом!");
					SendInf(i, "Посмотреть свои лицензии можно через команду - /lic");

					pData[i][pLicenses][LIC_BOAT] = 1;

					SetPlayerVirtualWorld(i, 0);

					UpdatePlayerData(i, "licBoat", 1);

					check_quest_prize_start(i, 10);
					check_quest_prize_start(i, 9);

					DestroyVehicle(carid);
					SetPlayerPosEx(i, -451.5421,-48.9278,2.7685,0.8231);


					DeletePVarNew(i, "autoschool_type");
					DeletePVarNew(i, "autoschool_route");
					DisablePlayerRaceCheckpoint(i);
				}
			}
			else
			{
				random_phrase_exam_drive_b(i, route);
				SetPlayerRaceCheckpoint(i, 3, autoschool_route_boat[route][0], autoschool_route_boat[route][1], autoschool_route_boat[route][2], autoschool_route_boat[next_route][0], autoschool_route_boat[next_route][1], autoschool_route_boat[next_route][2], 4.0);
			}
		}
		case 3:
		{

			if(route == sizeof autoschool_route_fly - 1)
			{
				new Float:car_health;
				GetVehicleHealth(carid, car_health);
				if(car_health < 900)
				{
					SCM(i, -1, "");
					SendErr(i, "Вы повредили транспортное средство и провалили практический экзамен в автошколе!");

					RepairVehicle(carid);
					SetVehicleToRespawn(carid);

					DeletePVarNew(i, "autoschool_type");
					DeletePVarNew(i, "autoschool_route");
					DisablePlayerRaceCheckpoint(i);
				}
				else
				{
					SCM(i, -1, "");
					SendInf(i, "Поздравляем! Вы успешно сдали практический экзамен и получили права на управление воздушным транспортом!");
					SendInf(i, "Посмотреть свои лицензии можно через команду - /lic");

					pData[i][pLicenses][LIC_FLY] = 1;

					check_quest_prize_start(i, 10);
					check_quest_prize_start(i, 8);

					SetPlayerVirtualWorld(i, 0);

					UpdatePlayerData(i, "licFly", 1);

					DestroyVehicle(carid);

					DeletePVarNew(i, "autoschool_type");
					DeletePVarNew(i, "autoschool_route");
					DisablePlayerRaceCheckpoint(i);
				}
			}
			else
			{
				random_phrase_exam_drive_f(i, route);
				SetPlayerRaceCheckpoint(i, 3, autoschool_route_fly[route][0], autoschool_route_fly[route][1], autoschool_route_fly[route][2], autoschool_route_fly[next_route][0], autoschool_route_fly[next_route][1], autoschool_route_fly[next_route][2], 6.0);
			}
		}
	}
	route ++;

	if(debug_mode)
	{
		printf("[autoschool_route]: Времени затрачено: <%d мс>" , GetTickCount() - time);
	}
	
	return SetPVarIntNew(i, "autoschool_route", route);
}

stock autoschool_end_lesson(i)
{
	if(!GetPVarIntNew(i, "autoschool_type")) return true;
	new carid = GetPlayerVehicleID(i);
	DestroyVehicle(carid);

	DeletePVarNew(i, "autoschool_type");
	DeletePVarNew(i, "autoschool_route");
	DisablePlayerRaceCheckpoint(i);

	SendInf(i, "Практический экзамен завершен!");
	return true;
}




stock dialog_autoschool_theory_1(playerid)
{
	return SPD(playerid, DIALOG_AUTOSCHOOL_THEORY_1, DIALOG_STYLE_MSGBOX, !""cBLUE"Правила дорожного движения", !"\
	"cBLUE"-"cWH" В темное время суток и в условиях недостаточной видимости независимо от освещения дороги, \n\
	а также в тоннелях на движущемся транспортном средстве должны быть включены следующие световые приборы:\n\n\
	"cBLUE"-"cWH" На всех механических транспортных средствах - фары дальнего или ближнего света \n\
	"cBLUE"-"cWH" На велосипедах - фары или фонари, на гужевых повозках - фонари (при их наличии)\n\
	"cBLUE"-"cWH" На прицепах и буксируемых механических транспортных средствах - габаритные огни\
	\n\
	", !"Далее", !"Отмена");
}

stock dialog_autoschool_theory_2(playerid)
{
	return SPD(playerid, DIALOG_AUTOSCHOOL_THEORY_2, DIALOG_STYLE_MSGBOX, !""cBLUE"Правила дорожного движения", !"\
	"cBLUE"-"cWH" Подача сигнала указателями поворота или рукой должна производиться заблаговременно\n\
	до начала выполнения маневра и прекращаться немедленно после его завершения \n\
	(подача сигнала рукой может быть закончена непосредственно перед выполнением маневра) \n\n\
	При этом сигнал не должен вводить в заблуждение других участников движения\n\
	Подача сигнала не дает водителю преимущества и не освобождает его от принятия мер предосторожности\
	\n\
	", !"Далее", !"Назад");
}

stock dialog_autoschool_theory_3(playerid)
{
	return SPD(playerid, DIALOG_AUTOSCHOOL_THEORY_3, DIALOG_STYLE_MSGBOX, !""cBLUE"Правила дорожного движения", !"\
	"cBLUE"-"cWH" При присутствии оранжевой и белой дорожной разметкой\n\
	Водители должны руководствоваться временной разметкой оранжевого цвета, \n\
	которая применяется при изменении организации движения, например, \n\
	в связи с производством ремонтных работ на дороге\
	\n\
	", !"Далее", !"Назад");
}

stock dialog_autoschool_theory_4(playerid)
{
	return SPD(playerid, DIALOG_AUTOSCHOOL_THEORY_4, DIALOG_STYLE_MSGBOX, !""cBLUE"Правила дорожного движения", !"\
	"cBLUE"-"cWH" На оси транспортного средства запрещено устанавливать шины различных размеров, \n\
	конструкций (радиальной, диагональной, камерной, бескамерной), моделей, с различными рисунками протектора, \n\
	морозостойкие и неморозостойкие, новые и восстановленные, новые и с углубленным рисунком протектора. \n\
	А так же ошипованные и неошипованные шины!\
	\n\
	", !"Далее", !"Назад");
}

stock dialog_autoschool_theory_5(playerid)
{
	return SPD(playerid, DIALOG_AUTOSCHOOL_THEORY_5, DIALOG_STYLE_MSGBOX, !""cBLUE"Правила дорожного движения", !"\
	"cBLUE"-"cWH" При прохождении поворота на ТС действует центробежная сила, \n\
	которая возрастает с увеличением скорости и стремится сместить ТС к внешней стороне закругления дороги. \n\
	Занос или снос ТС может возникнуть при проезде поворота из-за большой скорости движения, \n\
	торможения или низкого коэффициента сцепления. \n\
	Антиблокировочная тормозная система, предназначенная для предотвращения блокировки колес ТС, может снизить вероятность \n\
	возникновения заноса или сноса при торможении, но не может исключить возможность их возникновения.\
	\n\
	", !"Далее", !"Назад");
}

stock dialog_autoschool_theory_6(playerid)
{
	return SPD(playerid, DIALOG_AUTOSCHOOL_THEORY_6, DIALOG_STYLE_MSGBOX, !""cBLUE"Правила дорожного движения", !"\
	"cBLUE"-"cWH" При отсутствии или неисправности аварийной сигнализации на буксируемом \n\
	механическом транспортном средстве на его задней части должен быть закреплен знак аварийной остановки.\
	\n\
	", !"Далее", !"Назад");
}

stock dialog_autoschool_theory_7(playerid)
{
	return SPD(playerid, DIALOG_AUTOSCHOOL_THEORY_7, DIALOG_STYLE_MSGBOX, !""cBLUE"Правила дорожного движения", !"\
	"cBLUE"-"cWH" Водителю обгоняемого транспортного средства запрещается препятствовать обгону \n\
	посредством повышения скорости движения или иными действиями.\
	\n\
	", !"Далее", !"Назад");
}

stock dialog_autoschool_theory_8(playerid)
{
	return SPD(playerid, DIALOG_AUTOSCHOOL_THEORY_8, DIALOG_STYLE_MSGBOX, !""cBLUE"Правила дорожного движения", !"\
	"cBLUE"-"cWH" Дальний свет должен быть переключен на ближний:\n\n\
	"cBLUE"-"cWH" В населенных пунктах, если дорога освещена\n\
	"cBLUE"-"cWH" При встречном разъезде на расстоянии не менее чем за 150 м до транспортного средства, \n\
	а также и при большем, если водитель встречного транспортного средства периодическим переключением \n\
	света фар покажет необходимость этого\n\
	"cBLUE"-"cWH" В любых других случаях для исключения возможности ослепления водителей как встречных, так и попутных транспортных средств.\n\
	При ослеплении водитель должен включить аварийную сигнализацию и, не меняя полосу движения, снизить скорость и остановиться.\
	\n\
	", !"Далее", !"Назад");
}

stock dialog_autoschool_theory_10(playerid)
{
	return SPD(playerid, DIALOG_AUTOSCHOOL_CAR_EXAM, DIALOG_STYLE_MSGBOX, !""cBLUE"Правила дорожного движения", !"\
	"cBLUE"Дополнительная информация:\n\n\
	"cBLUE"'Дорога'"cWH" - обустроенная или приспособленная и используемая для движения транспортных средств полоса земли \n\
	либо поверхность искусственного сооружения. \n\
	Дорога включает в себя одну или несколько проезжих частей, а также трамвайные пути, \n\
	тротуары, обочины и разделительные полосы при их наличии.\
	\n\
	", !"Экзамен!", !"Позже");
}


stock create_school_exam_vert(playerid)
{
	if(GetPVarIntNew(playerid, "spawn_veh_exam_school"))
		return true;

	new 
		c1 = 3,
		c2 = 3;	

	new 
		exam_vert = CreateVehicle(487, -568.6249,39.5610,15.1787,0.1353, c1, c2, 600);	

	SetPVarIntNew(playerid, "first_enter_veh", 1);	

	PutPlayerInVehicleEx(playerid, exam_vert, 0);

	new 
		vw = playerid+random(500);

	SetPlayerVirtualWorld(playerid, vw);
	SetVehicleVirtualWorld(exam_vert, vw);


	vehicle[exam_vert][cFuel] = 90.0;
	vehicle[exam_vert][cHealth] = 1000.0;
	vehicle[exam_vert][cIsCreated] = true;

	vehicle[exam_vert][cOwnTo] = VEHICLES_AUTOSCHOOL;

	vehicle[exam_vert][cLock] = 2;

	vehicle[exam_vert][consumables_oil] = 1000.0;

	vehicle_lock_status(exam_vert, true);

	SetPVarIntNew(playerid, "spawn_veh_exam_school", 1);

	return true;
}

stock create_school_exam_boat(playerid)
{
	if(GetPVarIntNew(playerid, "spawn_veh_exam_school"))
		return true;

	new 
		c1 = 3,
		c2 = 3;	

	new 
		exam_boat = CreateVehicle(472, -457.3282,-54.7433,0.0780,181.7077, c1, c2, 600);	

	SetPVarIntNew(playerid, "first_enter_veh", 1);	

	PutPlayerInVehicleEx(playerid, exam_boat, 0);

	new 
		vw = playerid+random(500);

	SetPlayerVirtualWorld(playerid, vw);
	SetVehicleVirtualWorld(exam_boat, vw);


	vehicle[exam_boat][cFuel] = 90.0;
	vehicle[exam_boat][cHealth] = 1000.0;
	vehicle[exam_boat][cIsCreated] = true;

	vehicle[exam_boat][cOwnTo] = VEHICLES_AUTOSCHOOL;

	vehicle[exam_boat][cLock] = 2;

	vehicle[exam_boat][consumables_oil] = 1000.0;

	vehicle_lock_status(exam_boat, true);

	SetPVarIntNew(playerid, "spawn_veh_exam_school", 1);

	return true;
}

stock create_school_exam_veh(playerid)
{
	if(!GetPVarIntNew(playerid, "autoschool_type"))
	{
		SendErr(playerid, "Тебе еще рано сдавать практическую часть!");
		return RemovePlayerFromVehicleEx(playerid);
	}


	if(GetPVarIntNew(playerid, "spawn_veh_exam_school"))
		return true;

	new 
		c1 = 3,
		c2 = 3;	

	new 
		exam_veh = CreateVehicle(410, -527.0684,20.9159,12.8804,182.4318, c1, c2, 600);	

	new 
		vw = playerid+random(500);

	SetPlayerVirtualWorld(playerid, vw);
	SetVehicleVirtualWorld(exam_veh, vw);

	SetPVarIntNew(playerid, "first_enter_veh", 1);

	PutPlayerInVehicleEx(playerid, exam_veh, 0);

	vehicle[exam_veh][cFuel] = 90.0;
	vehicle[exam_veh][cHealth] = 1000.0;
	vehicle[exam_veh][cIsCreated] = true;

	vehicle[exam_veh][cOwnTo] = VEHICLES_AUTOSCHOOL;

	vehicle[exam_veh][cLock] = 2;

	vehicle[exam_veh][consumables_oil] = 1000.0;

	vehicle_lock_status(exam_veh, true);

	SetPVarIntNew(playerid, "spawn_veh_exam_school", 1);


	return true;

}


stock random_phrase_exam_drive_v(playerid, route)
{

	switch(route)
	{
		case 0: 
		{
			SendClientMessage(playerid,CPINK,"Инструктор закрывает глаза чтобы насладиться последними моментами своей жизни");
			SCM(playerid, 0xFFFFFFFF, "{00CC00}[Инструктор] "cWH"А вы видимо не первый раз за рулем! Молодец!");
		}
		case 2: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Инструктор] "cWH"Куда ты так коробку передёргиваешь?! Плавно нажимай!");
		case 4:
		{
			SCM(playerid, 0xFFFFFFFF, "{00CC00}[Инструктор] "cWH"Хотите анекдот: что будет если одновременно нажать газ и тормоз..?");
			SCM(playerid, 0xFFFFFFFF, "{00CC00}[Инструктор] "cWH"Машина сделает скриншот!");
		}
		case 6: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Инструктор] "cWH"Ни что так не повышает квалификацию водителя, как едущая сзади машина ГАИ");
		case 9: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Инструктор] "cWH"Ехай, ехай... Неча по сторонам да в зеркала глазеть... Жми на газ");

		case 10: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Инструктор] "cWH"Куда так разогнался-то???? У нас щас букву сдует!!");

		case 12: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Инструктор] "cWH"Удовольствие от вождения это когда при повороте на право руль вращаешь налево");
		case 14: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Инструктор] "cWH"Если у тебя нет четырех колес, чувствуешь себя, будто стоишь на четвереньках");

		case 16: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Инструктор] "cWH"Вряд ли вы нарушите правила остановки на мосту...зачем вообще нужно останавливаться на мосту? Подвести самоубийцу? Ну да, пусть с комфортом доедет");

		case 20: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Инструктор] "cWH"Не все масла одинаково полезны! 'Олейна' или 'Злато' в двигатель заливать не надо!");

		case 24: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Инструктор] "cWH"И тут из-за поворота показывается он - вЫлАсЫпидист");

		case 26: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Инструктор] "cWH"Если займете место в организованной колоне, догонят и мосечкой в капот натычут");
		case 32: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Инструктор] "cWH"Ехай, ехай... Неча по сторонам да в зеркала глазеть... Жми на газ");
		case 35: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Инструктор] "cWH"Как говорится в книге… мы и благословлены и прокляты, вообще следи за дорогой!");

		case 37: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Инструктор] "cWH"Хочешь узнать какой человек — посмотри как он паркует машину! Надеюсь, что вы неплохой");
		case 39: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Инструктор] "cWH"Ни что так не повышает квалификацию водителя, как едущая сзади машина ГАИ. А, я это уже говорил!");
	}


	return true;
}

stock random_phrase_exam_drive_b(playerid, route)
{

	switch(route)
	{
		case 0: 
		{
			SCM(playerid, 0xFFFFFFFF, "{00CC00}[Капитан-Корабля] "cWH"Так-с, уже хорошо, продолжай в том же духе!");
		}
		case 2: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Капитан-Корабля] "cWH"В будущем на флот будут призывать только не умеющих плавать - они намного лучше защищают корабль");
		case 4: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Капитан-Корабля] "cWH"Да..я тоже всегда мечтал о личном катере!");
		case 6: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Капитан-Корабля] "cWH"Держи штурвал крепче, так, чтобы в случае чего он вместе с тобой уплыл!");
		case 8: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Капитан-Корабля] "cWH"Матросу не холодно, матросу - свежо! Это так, про службу!");
		case 10: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Капитан-Корабля] "cWH"Водка - это враг. А моряк врагов не боится и уничтожает");
		case 12: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Капитан-Корабля] "cWH"Пьяный пехотинец страшнее танка. А пьяный матрос - страшнее пехотинца");

		case 15: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Капитан-Корабля] "cWH"Если хочешь жить в уюте – ешь и пей в чужой каюте!");
		case 18: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Капитан-Корабля] "cWH"Всякая инициатива на флоте наказуема");
		case 20: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Капитан-Корабля] "cWH"Хочешь плавать на «авось» – лучше сразу море брось");
		case 24: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Капитан-Корабля] "cWH"Чтобы богатым быть, надо у моря жить");
		case 27: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Капитан-Корабля] "cWH"Плохих навигационных инструментов нет, есть плохие штурманы");
		case 30: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Капитан-Корабля] "cWH"Ладно, удачи тебе, покатаешь еще меня на своей яхте!");
	}


	return true;
}

stock random_phrase_exam_drive_f(playerid, route)
{

	switch(route)
	{
		case 0: 
		{
			SCM(playerid, 0xFFFFFFFF, "{00CC00}[Главный Пилот] "cWH"Так-с, уже хорошо, продолжай в том же духе!");
		}
		case 2: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Главный Пилот] "cWH"Чаще летаешь — лучше живешь. Реже летаешь — дольше живешь");
		case 4: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Главный Пилот] "cWH"Отличный тот пилот, который используя отличные знания, избегает ситуаций, требующих отличных навыков");
		case 6: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Главный Пилот] "cWH"Если летчик — это уже хороший. Если не хороший — значит, и не летчик");
		case 8: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Главный Пилот] "cWH"Летчик должен знать, куда посмотреть, что увидеть и что при увиденном сделать");
		case 10: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Главный Пилот] "cWH"Главное правило авиации — всяко может случиться");
		case 12: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Главный Пилот] "cWH"Самый безопасный контакт — его отсутствие");

		case 15: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Главный Пилот] "cWH"Скорость — это жизнь: чем больше, тем лучше");
		case 18: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Главный Пилот] "cWH"Здоровье надо не укреплять, а беречь");
		case 21: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Главный Пилот] "cWH"У летчика не бывает вопросов. Если они появляются, он идет с ними к врачу");
		case 23: return SCM(playerid, 0xFFFFFFFF, "{00CC00}[Главный Пилот] "cWH"Ладно, удачи тебе, покатаешь еще меня на своем вертолете!");
	}


	return true;
}