; Основные настройки проекта
server_name = BLESS KAZAKHSTAN
nameserver = BLESS KAZAKHSTAN

; Стартовый бонус
bonus_money = 40000000
money = 40000000
bonus_donate = 2000
donate = 2000
bonus_lvl = 1
lvl = 1
vip = 1

; Прочие настройки
whitelist = 0

; Сообщение команды /cc
cc_message = {FF0000}Чат был очищен администрацией

; Музыка при входе (прямая ссылка на MP3)
audio_url = http://bh-audio-cdn.srv00.com/background_guide_standart.mp3
