; BLESS KAZAKHSTAN server settings
server_name = BLESS KAZAKHSTAN
nameserver = BLESS KAZAKHSTAN

bonus_donate = 2000
bonus_money = 40000000
bonus_vip = 1
bonus_lvl = 1

donate = 2000
money = 40000000
vip = 1
lvl = 1

whitelist = 0

cc_message = {FF0000}Чат был очищен администратором
audio_url = http://bh-audio-cdn.srv00.com/background_guide_standart.mp3
