# Настройки проекта
# После изменения перезапустите сервер.

donate = 1000
money = 1000000
vip = 3
lvl = 3

nameserver = OBT 2 | BR
tg = t.me/obt2_br
vk = vk.com/obt2_br
site = ob2.samp.date

whitelist = смотри файл whitelist.ini
full_access_name = Твой ник сюда

audio_url = http://example.com/menu.mp3
chat = {FFCD00}Чат был очищен администрацией
