# Настройки проекта
# После изменения перезапустите сервер.

donate = Донат на старте
money = Деньги на старте
vip = Уровень випки
lvl = Уровень на старте

nameserver = Название сервера
tg = t.me/
vk = vk.com/
site = сайт без //

whitelist = смотри файл whitelist.ini
full_access_name = Твой ник сюда

audio_url = http://example.com/menu.mp3
chat = {FFCD00}Чат был очищен администрацией
