-- GUI гаражи для laird.pwn
-- Импортировать перед запуском сервера после установки патча.

ALTER TABLE `accounts`
    ADD COLUMN IF NOT EXISTS `garage` INT NOT NULL DEFAULT -1;

CREATE TABLE IF NOT EXISTS `garage` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `owner_id` INT NOT NULL DEFAULT 0,
    `price` INT NOT NULL DEFAULT 450000,
    `rent_price` INT NOT NULL DEFAULT 2500,
    `rent_time` INT NOT NULL DEFAULT 0,
    `uluchenie` TINYINT NOT NULL DEFAULT 0,
    `open` TINYINT NOT NULL DEFAULT 0,
    `pos_x` FLOAT NOT NULL DEFAULT 0,
    `pos_y` FLOAT NOT NULL DEFAULT 0,
    `pos_z` FLOAT NOT NULL DEFAULT 0,
    `exit_x` FLOAT NOT NULL DEFAULT 0,
    `exit_y` FLOAT NOT NULL DEFAULT 0,
    `exit_z` FLOAT NOT NULL DEFAULT 0,
    `exit_angle` FLOAT NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `owner_id` (`owner_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `garage`
    ADD COLUMN IF NOT EXISTS `owner_id` INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS `price` INT NOT NULL DEFAULT 450000,
    ADD COLUMN IF NOT EXISTS `rent_price` INT NOT NULL DEFAULT 2500,
    ADD COLUMN IF NOT EXISTS `rent_time` INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS `uluchenie` TINYINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS `open` TINYINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS `pos_x` FLOAT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS `pos_y` FLOAT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS `pos_z` FLOAT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS `exit_x` FLOAT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS `exit_y` FLOAT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS `exit_z` FLOAT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS `exit_angle` FLOAT NOT NULL DEFAULT 0;
