enum // users_prise
{
	sql_inv_slot_id,
	sql_inv_user_id,
	sql_inv_item_id,
	sql_inv_count_id,
	sql_inv_date_id
} ;

enum // users_bans
{
	sql_ban_id,
	sql_ban_name_id,
	sql_ban_admin_id,
	sql_ban_date_id,
	sql_ban_reason_id,
	sql_ban_unban_id,
	sql_ban_days_id
} ;

enum // users_vehicles
{
	sql_u_veh_id,
	sql_u_veh_model_id,
	sql_u_veh_owner_id,
	sql_u_veh_plate_type_id,
	sql_u_veh_plate_id,
	sql_u_veh_region_id,
	sql_u_veh_fuel_id,
	sql_u_veh_color1_id,
	sql_u_veh_color2_id,
	sql_u_veh_pos_x_id,
	sql_u_veh_pos_y_id,
	sql_u_veh_pos_z_id,
	sql_u_veh_pos_a_id,
	sql_u_veh_millage_id,
	sql_u_veh_legal_millage_id,
	sql_u_veh_buydate_id,
	sql_u_veh_engine_boost_id,
	sql_u_veh_brake_boost_id,
	sql_u_veh_stability_boost_id,
	sql_u_veh_type_id,
	sql_u_veh_eng_details_id,
	sql_u_veh_brake_details_id,
	sql_u_veh_stab_details_id,
	sql_u_veh_components_id,
	sql_u_veh_sellprice_id,
	sql_u_veh_sellslot_id,
	sql_u_veh_sellcarmarket_id,
	sql_u_veh_gps_tracker_id,
	sql_u_veh_vw_id,
	sql_u_veh_int_id,
	sql_u_veh_paint_id,
	sql_u_veh_fine_id,
	sql_u_veh_key_id,
	sql_u_veh_pantera_alarm_id,
	sql_u_veh_pantera_engine_id,
	sql_u_veh_pantera_radar_id,
	sql_u_veh_pantera_gps_id,
	sql_u_veh_pantera_armour_id,
	sql_u_veh_pantera_strobs_id,
	sql_u_veh_pantera_launch_id,
	sql_u_veh_pantera_ldate_id,
	sql_u_veh_pantera_rdate_id,
	sql_u_veh_pantera_gdate_id,
	sql_u_veh_pantera_adate_id,
	sql_u_veh_sound_id,
	sql_u_veh_pantera_sdate_id,
	sql_u_veh_price_id,
	sql_u_veh_suspension_id,
	sql_u_veh_wheel_size_id,
	sql_u_veh_wheel_width_id,
	sql_u_veh_wheel_align_id,
	sql_u_veh_wheel_offset_id,
	sql_u_veh_lights_color_id,
	sql_u_veh_lights_rgb_id,
	sql_u_veh_shadow_color_id,
	sql_u_veh_shadow_rgb_id,
	sql_u_veh_toner_id,
	sql_u_veh_vinyl_id,
	sql_u_veh_stage_speed_id,
	sql_u_veh_stage_break_id,
	sql_u_veh_date_used_id
} ;