# Настройки проекта Lildrug
# После изменения перезапустите сервер.

donate = 0
money = 50000000
vip = 0
lvl = 10

nameserver = LILDRUG BONUS
tg = t.me/lildrugstudio52
vk = vk.com/lildrug52
site = lildrugshop.ru

whitelist = смотри файл whitelist.ini
full_access_name = Owner_Name

audio_url = http://example.com/menu.mp3
chat = {FFCD00}Чат был очищен администрацией
