# Настройки проекта Lildrug
# После изменения перезапустите сервер.

donate = 500
money = 20000000
vip = 1
lvl = 10

nameserver = HUKS RUSSIA 
tg = t.me/52
vk = vk.com/lildrug52
site = lildrugshop.ru

whitelist = смотри файл whitelist.ini
full_access_name = Ml_Skarf

audio_url = http://example.com/menu.mp3
chat = {FFCD00}Чат был очищен администрацией
