# Настройки проекта LAIRD
# После изменения перезапустите сервер.

donate = 7500
money = 225000000
vip = 1
lvl = 1

nameserver = SELL RUSSIA
tg = t.me/lonexs
vk = vk.com/lonexs
site = example.com

whitelist = смотри файл whitelist.ini
full_access_name = Owner_Name

audio_url = http://example.com/menu.mp3
chat = {FFCD00}Чат был очищен администрацией
