# Настройки проекта LAIRD
# После изменения перезапустите сервер.

donate = 5000
money = 350000000
vip = 1
lvl = 1

nameserver = KLEOS RUSSIA
tg = t.me/kleos_dev
vk = none
site = soon

whitelist = смотри файл whitelist.ini
full_access_name = Green_Developer

audio_url = http://example.com/menu.mp3
chat = {FFCD00}Чат был очищен администрацией
