# Настройки проекта LAIRD
# После изменения перезапустите сервер.

donate = 0
money = 0
vip = 1
lvl = 1

nameserver = KLEOS RUSSIA
tg = t.me/kleos_dev
vk = none
site = none

whitelist = смотри файл whitelist.ini
full_access_name = Owner_Name

audio_url = http://example.com/menu.mp3
chat = {FFCD00}Чат был очищен администрацией
