# Настройки проекта
# После изменения перезапустите сервер.

donate = 670000
money = 67
vip = 3
lvl = 1

nameserver = 67
tg = 67
vk = 67
site = 67

whitelist = смотри файл whitelist.ini
full_access_name = Твой ник сюда

audio_url = http://example.com/menu.mp3
chat = {FFCD00}Чат был очищен администрацией
