# Настройки проекта LAIRD
# После изменения перезапустите сервер.

donate = 500
money = 80000000
vip = 2
lvl = 15

nameserver = Rollso Rp
tg = none
vk = none
site = none

whitelist = смотри файл whitelist.ini
full_access_name = Owner_Name

audio_url = http://example.com/menu.mp3
chat = {FFCD00}Чат был очищен администрацией
