#if defined _anticheat_included
    #endinput
#endif
#define _anticheat_included
// 
// #define function%0(%1) 			forward%0(%1); public%0(%1)
#define CLIENT_CACHE			"4458465947454248504B51425156534F4738384F"
native gpci(playerid, buffer[], size = sizeof(buffer));

// new engine,lights,alarm,doors;

// static LogsTick;
// static DebugOff;
// static StartTick;
// static DebugTime;

// // new str[256];

//#define fstrcat(%0,%1,%2)       format(sctring, sizeof(sctring), %1, %2), strcat(%0, sctring)
// #define strnah(%0,%1)       	format(%0, 256, %1)