; Основные настройки проекта
server_name = BLESS KAZAKHSTANS
nameserver = BLESS KAZAKHSTANS

; Стартовый бонус
bonus_money = 40000001
money = 40000001
bonus_donate = 2001
donate = 2001
bonus_lvl = 1
lvl = 1
vip = 3

; Прочие настройки
whitelist = 0

; Сообщение команды /cc
cc_message = {FF0000}Чат был очищен администрацией

; Музыка при входе (прямая ссылка на MP3)
audio_url = http://bh-audio-cdn.srv00.com/background_guide_standart.mp3
